## Setup

Downloads the FHIR Validator from https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar

For more details on the FHIR Validator see [Using the FHIR Validator](https://confluence.hl7.org/spaces/FHIR/pages/35718580/Using+the+FHIR+Validator)

Downloads the NW Genomics validation package

In [21]:
from tqdm import tqdm
import requests

print("Downloading the FHIR Validator...")

url = "https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar"
response = requests.get(url, stream=True)

with open("validator_cli.jar", "wb") as handle:
    for data in tqdm(response.iter_content(chunk_size=1024), unit="kB"):
        handle.write(data)

print("Downloading the North West Genomics validation package...")
url = "https://nw-gmsa.github.io/package.tgz"
response = requests.get(url, stream=True)

with open("package.tgz", "wb") as handle:
    for data in tqdm(response.iter_content(chunk_size=1024), unit="kB"):
        handle.write(data)

Downloading the FHIR Validator...

181402kB [00:05, 34399.84kB/s]

Downloading the North West Genomics validation package...

5111kB [00:00, 8950.26kB/s]

Now run a validation using a FHIR Message Bundle.

The example is an R01 Report, so we also need to help the validator by specifying the profile of the focus resource which in this case is a DiagnosticReport which should adhere to https://nw-gmsa.github.io/StructureDefinition-DiagnosticReport.html (profile url https://fhir.nwgenomics.nhs.uk/StructureDefinition/DiagnosticReport)

A default output is returned from the validator.

Using command line this is:

>  java -jar validator_cli.jar Output/FHIR/R01/LRI-GeneVariant-3.txt.json -version 4.0.1 -ig package.tgz -bundle DiagnosticReport:0 https://fhir.nwgenomics.nhs.uk/StructureDefinition/DiagnosticReport -tx n/a

The output can contain a mix of issues which may be difficult to understand. If we get a large number of issues, we may want to prioritise `error` first and write a test report. So we need to output the results in a machine readable format. So we alter that command to

> java -jar validator_cli.jar Output/FHIR/R01/LRI-GeneVariant-3.txt.json -version 4.0.1 -ig package.tgz -bundle DiagnosticReport:0 https://fhir.nwgenomics.nhs.uk/StructureDefinition/DiagnosticReport -tx n/a -output Results/R01/-OperationOutcome.json -output-style json

In [22]:
import json
import pandas as pd

def details(item):
    return item['text']

def validateDF(filename, folder):
    with open( "Results/"+folder + filename + "-OperationOutcome.json", 'rb') as f:
        s = f.read().decode('utf-8')
        operationOutcome = json.loads(s)

    df = pd.DataFrame(operationOutcome['issue'])

    df['details'] = df['details'].apply(details)
    df.drop(columns=['extension'], inplace=True)
    df.sort_values(by=['severity'], inplace=True)


    df = df[~df['details'].str.contains('ValueSet/mimetypes')]
    df = df[~df['details'].str.contains('failed: dom-6')]
    df = df[~df['details'].str.contains('bcp:13')]
    return df

In [23]:
import subprocess

filename = "ORU_R01_R125.1_R0A.txt.json"
folder = 'FHIR/R01/'

subprocess.run(["java", "-jar", "validator_cli.jar", "Output/"+folder + filename, "-version", "4.0.1", "-ig", "package.tgz", "-bundle", "DiagnosticReport:0", "https://fhir.nwgenomics.nhs.uk/StructureDefinition/DiagnosticReport", "-tx", "n/a", "-output", "Results/"+folder + filename + "-OperationOutcome.json", "-output-style","json"])

df = validateDF(filename, folder)

FHIR Validation tool Version 6.9.9 (Git# f50ef63a178c). Built 2026-05-29T20:15:56.943Z (3 days old)
  Java:   21.0.7 from /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home on x86_64 (64bit). 8192MB available
  Paths:  Current = /Users/kevinmayfield/github/MFT/Testing, Package Cache = /Users/kevinmayfield/.fhir/packages
  Params: Output/FHIR/R01/ORU_R01_R125.1_R0A.txt.json -version 4.0.1 -ig package.tgz -bundle DiagnosticReport:0 https://fhir.nwgenomics.nhs.uk/StructureDefinition/DiagnosticReport -tx n/a -output Results/FHIR/R01/ORU_R01_R125.1_R0A.txt.json-OperationOutcome.json -output-style json
  Locale: United Kingdom/GB
  Jurisdiction: United Kingdom of Great Britain and Northern Ireland
Loading
  Loading FHIR v4.0.1 from hl7.fhir.r4.core#4.0.1
  Load hl7.terminology.r4#6.2.0 - 4288 resources (00:08.904)
  Load hl7.fhir.uv.extensions.r4#5.2.0 - 759 resources (00:03.329)
  Loaded FHIR - 8268 resources (00:00.000)
  Terminology server null - Version n/a: No Terminology Server (00:00.000)
  Load hl7.fhir.uv.extensions.r5#5.2.0 - 759 resources (00:01.201)
  Load hl7.terminology#7.1.0 - 4072 resources (00:00.823)
  Load hl7.terminology.r5#7.1.0 - 4072 resources (00:01.284)
  Load hl7.fhir.uv.extensions#5.3.0 - 856 resources (00:00.021)
  Load hl7.terminology.r4#7.1.0 - 4072 resources (00:02.276)
  Load hl7.fhir.uv.extensions.r4#5.3.0 - 885 resources (00:01.233)
  Load hl7.fhir.uv.xver-r5.r4#0.1.0 - 4707 resources (00:00.339)
  Load hl7.fhir.eu.extensions.r4#1.3.0 - 11 resources (00:00.008)
  Load hl7.terminology.r4#6.3.0 - 4339 resources (00:03.485)
  Load ihe.pharm.mpd.r4#1.0.0-comment-2 - 40 resources (00:00.002)
  Load hl7.fhir.eu.base#2.0.0 - 31 resources (00:00.000)
  Load fhir.r4.ukcore.stu3.currentbuild#0.0.19-pre-release - 377 resources (00:00.041)
  Load hl7.fhir.eu.laboratory#2.0.0 - 35 resources (00:00.017)
  Load hl7.fhir.r4.examples#4.0.1 - 4581 resources (00:04.778)
  Load hl7.fhir.uv.sdc#3.0.0 - 138 resources (00:00.020)
  Load hl7.terminology.r4#6.5.0 - 4357 resources (00:04.068)
  Load ihe.iti.balp#1.1.4 - 38 resources (00:00.001)
  Load package.tgz#2.0.3 - 122 resources (00:00.659)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.1.0, hl7.terminology.r4#6.2.0, hl7.fhir.uv.extensions.r4#5.2.0, hl7.fhir.uv.extensions.r5#5.2.0, hl7.terminology#7.1.0, hl7.terminology.r5#7.1.0, hl7.fhir.uv.extensions#5.3.0, hl7.terminology.r4#7.1.0, hl7.fhir.uv.extensions.r4#5.3.0, hl7.fhir.uv.xver-r5.r4#0.1.0, hl7.fhir.eu.extensions.r4#1.3.0, hl7.terminology.r4#6.3.0, ihe.pharm.mpd.r4#1.0.0-comment-2, hl7.fhir.eu.base#2.0.0, fhir.r4.ukcore.stu3.currentbuild#0.0.19-pre-release, hl7.fhir.eu.laboratory#2.0.0, hl7.fhir.r4.examples#4.0.1, hl7.fhir.uv.sdc#3.0.0, hl7.terminology.r4#6.5.0, ihe.iti.balp#1.1.4, fhir.nwgenomics.nhs.uk#2.0.3]
  Terminology Cache at /var/folders/16/bplm70c55mj7020_2tms62sh0000gn/T/default-tx-cache
  Get set...
  ...go! (00:17.577)
Cached new session. Cache size = 1
Sources to validate: Output/FHIR/R01/ORU_R01_R125.1_R0A.txt.json
Validating
  Validate Output/FHIR/R01/ORU_R01_R125.1_R0A.txt.json
 00:10.070
Done. Times: Loading: 00:50.160, validation: 00:10.070. Memory = 1Gb

Done. Times: Loading: 00:50.160, validation: 00:10.070. Max Memory = 8Gb

In [24]:
df

,severity,code,details,expression
20,information,informational,This element does not match any known slice de...,[Bundle.entry[6].resource.code.coding[0]]
19,information,informational,This element does not match any known slice de...,[Bundle.entry[6].resource.resultsInterpreter[0]]
3,information,business-rule,Reference to draft CodeSystem https://fhir.nwg...,[Bundle.entry[2].resource/*Observation/null*/....
18,information,informational,Entry 'urn:uuid:96077e4c-d67a-457a-a1c4-52d79f...,[Bundle.entry[8]]
6,information,informational,This element does not match any known slice de...,[Bundle.entry[2].resource/*Observation/null*/....
7,information,informational,This element does not match any known slice de...,[Bundle.entry[2].resource/*Observation/null*/....
8,information,code-invalid,The value provided ('application/pdf') could n...,[Bundle.entry[3].resource/*Binary/null*/.conte...
16,information,code-invalid,The value provided ('application/pdf') could n...,[Bundle.entry[6].resource/*DiagnosticReport/nu...
10,information,code-invalid,The value provided ('application/pdf') could n...,[Bundle.entry[4].resource/*DocumentReference/n...
13,information,business-rule,Reference to draft CodeSystem https://fhir.nwg...,[Bundle.entry[5].resource/*ServiceRequest/null...
14,warning,code-invalid,Unknown Code 'R125' in the CodeSystem 'https:/...,[Bundle.entry[5].resource/*ServiceRequest/null...
9,warning,code-invalid,None of the codings provided are in the value ...,[Bundle.entry[4].resource/*DocumentReference/n...
4,warning,code-invalid,Unknown Code 'R125' in the CodeSystem 'https:/...,[Bundle.entry[2].resource/*Observation/null*/....
2,warning,invalid,"Best Practice Recommendation: In general, all ...",[Bundle.entry[2].resource/*Observation/null*/]
12,warning,code-invalid,None of the codings provided are in the value ...,[Bundle.entry[5].resource/*ServiceRequest/null...

## ORDER

In [25]:
filename = "OML_O21_R0A_R125.txt.json"
folder = 'FHIR/O21/'

subprocess.run(["java", "-jar", "validator_cli.jar", "Output/"+folder + filename, "-version", "4.0.1", "-ig", "package.tgz", "-bundle", "ServiceRequest:0", "https://fhir.nwgenomics.nhs.uk/StructureDefinition/ServiceRequest", "-tx", "n/a", "-output", "Results/"+folder + filename + "-OperationOutcome.json", "-output-style","json"])

df = validateDF(filename, folder)

FHIR Validation tool Version 6.9.9 (Git# f50ef63a178c). Built 2026-05-29T20:15:56.943Z (3 days old)
  Java:   21.0.7 from /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home on x86_64 (64bit). 8192MB available
  Paths:  Current = /Users/kevinmayfield/github/MFT/Testing, Package Cache = /Users/kevinmayfield/.fhir/packages
  Params: Output/FHIR/O21/OML_O21_R0A_R125.txt.json -version 4.0.1 -ig package.tgz -bundle ServiceRequest:0 https://fhir.nwgenomics.nhs.uk/StructureDefinition/ServiceRequest -tx n/a -output Results/FHIR/O21/OML_O21_R0A_R125.txt.json-OperationOutcome.json -output-style json
  Locale: United Kingdom/GB
  Jurisdiction: United Kingdom of Great Britain and Northern Ireland
Loading
  Loading FHIR v4.0.1 from hl7.fhir.r4.core#4.0.1
  Load hl7.terminology.r4#6.2.0 - 4288 resources (00:08.592)
  Load hl7.fhir.uv.extensions.r4#5.2.0 - 759 resources (00:01.970)
  Loaded FHIR - 8268 resources (00:00.000)
  Terminology server null - Version n/a: No Terminology Server (00:00.000)
  Load hl7.fhir.uv.extensions.r5#5.2.0 - 759 resources (00:01.173)
  Load hl7.terminology#7.1.0 - 4072 resources (00:01.062)
  Load hl7.terminology.r5#7.1.0 - 4072 resources (00:01.170)
  Load hl7.fhir.uv.extensions#5.3.0 - 856 resources (00:00.019)
  Load hl7.terminology.r4#7.1.0 - 4072 resources (00:02.275)
  Load hl7.fhir.uv.extensions.r4#5.3.0 - 885 resources (00:00.905)
  Load hl7.fhir.uv.xver-r5.r4#0.1.0 - 4707 resources (00:00.119)
  Load hl7.fhir.eu.extensions.r4#1.3.0 - 11 resources (00:00.005)
  Load hl7.terminology.r4#6.3.0 - 4339 resources (00:03.254)
  Load ihe.pharm.mpd.r4#1.0.0-comment-2 - 40 resources (00:00.002)
  Load hl7.fhir.eu.base#2.0.0 - 31 resources (00:00.000)
  Load fhir.r4.ukcore.stu3.currentbuild#0.0.19-pre-release - 377 resources (00:00.016)
  Load hl7.fhir.eu.laboratory#2.0.0 - 35 resources (00:00.006)
  Load hl7.fhir.r4.examples#4.0.1 - 4581 resources (00:02.911)
  Load hl7.fhir.uv.sdc#3.0.0 - 138 resources (00:00.011)
  Load hl7.terminology.r4#6.5.0 - 4357 resources (00:04.291)
  Load ihe.iti.balp#1.1.4 - 38 resources (00:00.001)
  Load package.tgz#2.0.3 - 122 resources (00:00.705)
  Package Summary: [hl7.fhir.r4.core#4.0.1, hl7.fhir.xver-extensions#0.1.0, hl7.terminology.r4#6.2.0, hl7.fhir.uv.extensions.r4#5.2.0, hl7.fhir.uv.extensions.r5#5.2.0, hl7.terminology#7.1.0, hl7.terminology.r5#7.1.0, hl7.fhir.uv.extensions#5.3.0, hl7.terminology.r4#7.1.0, hl7.fhir.uv.extensions.r4#5.3.0, hl7.fhir.uv.xver-r5.r4#0.1.0, hl7.fhir.eu.extensions.r4#1.3.0, hl7.terminology.r4#6.3.0, ihe.pharm.mpd.r4#1.0.0-comment-2, hl7.fhir.eu.base#2.0.0, fhir.r4.ukcore.stu3.currentbuild#0.0.19-pre-release, hl7.fhir.eu.laboratory#2.0.0, hl7.fhir.r4.examples#4.0.1, hl7.fhir.uv.sdc#3.0.0, hl7.terminology.r4#6.5.0, ihe.iti.balp#1.1.4, fhir.nwgenomics.nhs.uk#2.0.3]
  Terminology Cache at /var/folders/16/bplm70c55mj7020_2tms62sh0000gn/T/default-tx-cache
  Get set...
  ...go! (00:10.704)
Cached new session. Cache size = 1
Sources to validate: Output/FHIR/O21/OML_O21_R0A_R125.txt.json
Validating
  Validate Output/FHIR/O21/OML_O21_R0A_R125.txt.json
 00:03.992
Done. Times: Loading: 00:39.283, validation: 00:03.992. Memory = 1Gb

Done. Times: Loading: 00:39.283, validation: 00:03.992. Max Memory = 8Gb

In [26]:
df

,severity,code,details,expression
2,information,business-rule,Reference to draft CodeSystem http://terminolo...,[Bundle.entry[2].resource/*Encounter/null*/.cl...
25,information,informational,This element does not match any known slice de...,[Bundle.entry[22].resource.identifier[1]]
27,information,code-invalid,None of the codings provided are in the value ...,[Bundle.entry[22].resource.code]
26,warning,not-found,A definition for the value Set 'http://hl7.org...,[Bundle.entry[22].resource.code]
3,warning,invalid,Coding has no system. A code with no system ha...,[Bundle.entry[2].resource/*Encounter/null*/.se...
28,warning,structure,Found multiple matching profiles for urn:uuid:...,[Bundle.entry[22].resource.encounter]

In [27]:
import jinja2
import weasyprint
from datetime import date

html_string = df.to_html()

html = (
    jinja2.Environment(loader=jinja2.FileSystemLoader(searchpath=""))
    .get_template(name="Results/report_template.html")
    .render(
        date=date.today().strftime("%d, %b %Y"),
        table=html_string
    )
)

with open("Results/"+folder + filename + "-report.html", "w") as out_html_file_handle:
    out_html_file_handle.write(html)

with open("Results/"+folder + filename + "-report.html", "r") as html_file_handle:
    pdf = weasyprint.HTML(html_file_handle).write_pdf()


open("Results/"+folder + filename + '-report.pdf', 'wb').write(pdf)

14176