In [21]:
import pandas as pd

li=[]
# Read the CSV file
ney_data = pd.read_csv("Input/PDS/NEY.csv")

# View the first 5 rows
ney_data.head()

,NHS Number,Surname,Forename,Middle name,Other Name,Gender,Date Of Birth,Deceased,GP Surgery,Address line 1,Address line 2,Address line 3,Address line 4,Address line 5,Postcode
0,9737873947,NEWCASTLE,Rheana,NaN,NaN,F,11/06/2009,NaN,A89025,Byker,Newcastle,NaN,NaN,NaN,NE6 1SG
1,9737383222,LEEDS,Rob,NaN,NaN,M,17/01/1978,NaN,B86016,Maison Lane,NaN,NaN,LEEDS,NaN,LS8 2HH
2,9737873858,SHEFFIELD,Theon,NaN,NaN,M,12/09/1986,NaN,C88622,SPITAL STREET,Sheffield,NaN,NaN,NaN,S3 9LB
3,9737873963,HULL,Yara,NaN,NaN,F,23/04/1981,NaN,B81061,4 Centurion Way,Brough,NaN,NaN,NaN,HU15 1AY
4,9737873866,YORK,Euron,NaN,NaN,M,02/03/1982,✅,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
nw_data = pd.read_csv("Input/PDS/NW.csv")
nw_data.head()

,NHS Number,Surname,Forename,Middle name,Other Name,Gender,Date Of Birth,Deceased,GP Surgery,Address line 1,Address line 2,Address line 3,Address line 4,Address line 5,Postcode
0,944 930 5552,CHISLETT,Octavia,NaN,NaN,F,20/09/2008,NaN,NaN,1 RAVENSFIELD GARDENS,NaN,NaN,EPSOM,SURREY,KT19 0ST
1,9737383192,MANCHESTER,Sansa,NaN,NaN,F,21/09/1972,NaN,P84673,Oxford Rd,NaN,NaN,MANCHESTER,NaN,M13 9PL
2,9737383206,LIVERPOOL,Ned,NaN,NaN,M,18/06/1942,NaN,N82035,20 Forthlin Road,NaN,NaN,LIVERPOOL,NaN,L18 9TN
3,9737383214,LANCASTER,Jaime,NaN,M,27/07/1970,NaN,P81002,Dalton Square,NaN,NaN,NaN,LANCASTER,NaN,LA1 1PJ
4,9737383230,LONDON,Cersei,NaN,Cersei LANCASTER (maiden),F,03/10/1973,NaN,F83004,110 The Queen's Walk,NaN,NaN,LONDON,NaN,SE1 2AA

In [23]:
li.append(ney_data)
li.append(nw_data)

pds = pd.concat(li, axis=0, ignore_index=True)

pds

,NHS Number,Surname,Forename,Middle name,Other Name,Gender,Date Of Birth,Deceased,GP Surgery,Address line 1,Address line 2,Address line 3,Address line 4,Address line 5,Postcode
0,9737873947,NEWCASTLE,Rheana,NaN,NaN,F,11/06/2009,NaN,A89025,Byker,Newcastle,NaN,NaN,NaN,NE6 1SG
1,9737383222,LEEDS,Rob,NaN,NaN,M,17/01/1978,NaN,B86016,Maison Lane,NaN,NaN,LEEDS,NaN,LS8 2HH
2,9737873858,SHEFFIELD,Theon,NaN,NaN,M,12/09/1986,NaN,C88622,SPITAL STREET,Sheffield,NaN,NaN,NaN,S3 9LB
3,9737873963,HULL,Yara,NaN,NaN,F,23/04/1981,NaN,B81061,4 Centurion Way,Brough,NaN,NaN,NaN,HU15 1AY
4,9737873866,YORK,Euron,NaN,NaN,M,02/03/1982,✅,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9737873971,MIDDLESBOROUGH,Allanys,NaN,NaN,F,27/04/1947,NaN,A81027,1 WORSALL ROAD,Yarm,NaN,NaN,NaN,TS15 9DD
6,9737873874,SUNDERLAND,Corlys,NaN,NaN,M,22/03/1965,NaN,A89025,WASHINGTON CENTRE,WASHINGTON,NaN,NaN,NaN,NE38 7NQ
7,9737873998,DURHAM,Alicent,NaN,NaN,F,27/12/1993,NaN,A83011,26 GILESGATE,DURHAM,NaN,NaN,NaN,DH1 1QW
8,9737873882,BRADFORD,Rodrik,NaN,NaN,M,20/09/1942,NaN,B83055,COUSEN ROAD,GREAT HORTON,BRADFORD,NaN,NaN,BD7 3JX
9,944 930 5552,CHISLETT,Octavia,NaN,NaN,F,20/09/2008,NaN,NaN,1 RAVENSFIELD GARDENS,NaN,NaN,EPSOM,SURREY,KT19 0ST
10,9737383192,MANCHESTER,Sansa,NaN,NaN,F,21/09/1972,NaN,P84673,Oxford Rd,NaN,NaN,MANCHESTER,NaN,M13 9PL
11,9737383206,LIVERPOOL,Ned,NaN,NaN,M,18/06/1942,NaN,N82035,20 Forthlin Road,NaN,NaN,LIVERPOOL,NaN,L18 9TN
12,9737383214,LANCASTER,Jaime,NaN,M,27/07/1970,NaN,P81002,Dalton Square,NaN,NaN,NaN,LANCASTER,NaN,LA1 1PJ
13,9737383230,LONDON,Cersei,NaN,Cersei LANCASTER (maiden),F,03/10/1973,NaN,F83004,110 The Queen's Walk,NaN,NaN,LONDON,NaN,SE1 2AA
14,9737383249,BIRMINGHAM,Tommen,NaN,NaN,M,07/09/1999,NaN,M85124,Victoria Square,NaN,NaN,BIRMINGHAM,NaN,B3 3DQ
15,9737383257,WREXHAM,Myrcella,NaN,NaN,F,13/10/1999,NaN,Future: W91022 Current: N81082,"Ffordd, Mold Rd",Mold,NaN,WREXHAM,NaN,LL11 2AH
16,9737383265,NOTTINGHAM,Lyarra,NaN,NaN,F,05/01/1924,✅,C81010,NaN,NaN,NaN,NaN,NaN,NG10 1NP
17,9737383273,BOLTON,Ramsay,NaN,Ramsay ROCHDALE (old),M,13/05/1985,NaN,P84673,Victoria Sq,NaN,NaN,BOLTON,NaN,BL1 1RU
18,9737383281,CONGLETON,Margaery,NaN,NaN,F,11/02/1982,NaN,N81027,Town Hall,7 High Street,NaN,CONGLETON,NaN,CW12 1BN
19,9737383303,WARRINGTON,Olennas,NaN,NaN,F,20/07/1938,✅,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,9737383311,NORTHWICH,Mace,NaN,NaN,M,19/01/1957,NaN,N81087,Apple Market St,NaN,NaN,Northwich,NaN,CW9 5BB
21,9737383338,BUXTON,Lysa,NaN,NaN,F,01/01/1971,NaN,C81065,Market Place,NaN,NaN,Buxton,NaN,SK17 6EL
22,9737383346,HAWES,Ygritte,NaN,NaN,F,09/02/2023,NaN,B82045,Market Place,NaN,NaN,Hawes,NaN,DL8 3QN
23,9737383354,KENDAL,Tormund,NaN,NaN,M,07/12/1978,NaN,A82025,9a Lowther St,NaN,NaN,Kendal,NaN,LA9 4DA
24,9737383362,BROUGH,Gilly,NaN,NaN,F,01/07/1989,NaN,A82038,Townhead House,Brough,Sowerby,KIRKBY STEPHEN,NaN,CA17 4EG
25,9737383370,BLACKBURN,Robert,NaN,NaN,M,14/01/1965,NaN,Y02657,King William Street,NaN,NaN,Blackburn,Lancashire,BB1 7DY
26,9737383389,BURNLEY,Selyse,NaN,NaN,F,18/09/1967,NaN,Y00206,Manchester Road,NaN,NaN,Burnley,Lancashire,BB11 9SA
27,9737383397,TAMESIDE,Hodor,NaN,NaN,M,27/07/1960,NaN,P89020,Stockport Road,NaN,NaN,Tameside,NaN,OL7 0NS
28,(CHI Number),GLASGOW,Karsi,NaN,NaN,F,16/01/1982,NaN,NaN,J B Russell House,Gartnavel Royal Hospital Campus,1055 Great Western Road,Glasgow,NaN,G12 0XH
29,NaN,STREFORD,Syrio,NaN,NaN,M,29/05/1992,✅ 2025-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
import pandas as pd

# Read the CSV file
ctdna_data = pd.read_csv("NotGit/NEYGMSctDNAOrderData.csv")

# View the first 5 rows
ctdna_data.head()

,PatientAccessionIdentifier,NHSNumber,HospitalNumber,PatientFamilyName,PatientGivenName,DateOfBirth,AdministrativeSex,OrderingProviderIdentifier,OrderingProviderName,RequestingOrganisationCode,...,TestOrderDate,ObservationResultStatus,ObservationDateTime,ObservationIdentifierCode,ObservationIdentifierDescription,SpecimenTakenDateTime,SpecimenReceivedDateTime,SpecimenAccessionIdentifier,SpecimenTypeCode,SpecimenTypeDescription
0,228731,450 008 5475,RXR3178922,McAlernon,Linda,18 Mar 1956 12:00,Female,Osama_El-Masri_7759129,Dr Osama El-Masri,RXR,...,30 Jun 2026 12:00,NaN,NaN,NaN,NaN,29 Jun 2026 12:00,30 Jun 2026 12:00,S26-1K1L,SAMPLE: BL,Blood
1,32737,454 067 5729,RXR0817610,Dixon,Judith,05 Mar 1951 12:00,Female,Osama_El-Masri_7759129,Dr Osama El-Masri,RXR,...,30 Jun 2026 12:00,NaN,NaN,NaN,NaN,29 Jun 2026 12:00,30 Jun 2026 12:00,S26-1K1N,SAMPLE: BL,Blood
2,336292,460 578 5590,RXR3302855,Wearden,Stephen,25 Mar 1952 12:00,Male,Generic_Email_Contact,Lung Oncology CNS - Blackburn (ELHT),RXR,...,30 Jun 2026 12:00,NaN,NaN,NaN,NaN,29 Jun 2026 12:00,30 Jun 2026 12:00,S26-1K1Q,SAMPLE: BL,Blood
3,285232,408 363 1309,WL3847,Connelly,Caroline Mary,07 Dec 1975 12:00,Female,Rewan_Hanno_7780405,Dr Rewan Hanno,RHQ,...,30 Jun 2026 12:00,NaN,NaN,NaN,NaN,29 Jun 2026 12:00,30 Jun 2026 12:00,S26-1K1T,SAMPLE: BL,Blood
4,336384,408 706 2473,658357,Westerby,Heather,06 Nov 1981 12:00,Female,syed_shah_,Dr Syed Shah,RAE,...,30 Jun 2026 12:00,NaN,NaN,NaN,NaN,29 Jun 2026 12:00,30 Jun 2026 12:00,S26-1K6J,SAMPLE: BL,Blood

In [26]:
combined = pd.concat([ctdna_data, pds], axis=1)

combined.up

,PatientAccessionIdentifier,NHSNumber,HospitalNumber,PatientFamilyName,PatientGivenName,DateOfBirth,AdministrativeSex,OrderingProviderIdentifier,OrderingProviderName,RequestingOrganisationCode,...,Gender,Date Of Birth,Deceased,GP Surgery,Address line 1,Address line 2,Address line 3,Address line 4,Address line 5,Postcode
0,228731.0,450 008 5475,RXR3178922,McAlernon,Linda,18 Mar 1956 12:00,Female,Osama_El-Masri_7759129,Dr Osama El-Masri,RXR,...,F,11/06/2009,NaN,A89025,Byker,Newcastle,NaN,NaN,NaN,NE6 1SG
1,32737.0,454 067 5729,RXR0817610,Dixon,Judith,05 Mar 1951 12:00,Female,Osama_El-Masri_7759129,Dr Osama El-Masri,RXR,...,M,17/01/1978,NaN,B86016,Maison Lane,NaN,NaN,LEEDS,NaN,LS8 2HH
2,336292.0,460 578 5590,RXR3302855,Wearden,Stephen,25 Mar 1952 12:00,Male,Generic_Email_Contact,Lung Oncology CNS - Blackburn (ELHT),RXR,...,M,12/09/1986,NaN,C88622,SPITAL STREET,Sheffield,NaN,NaN,NaN,S3 9LB
3,285232.0,408 363 1309,WL3847,Connelly,Caroline Mary,07 Dec 1975 12:00,Female,Rewan_Hanno_7780405,Dr Rewan Hanno,RHQ,...,F,23/04/1981,NaN,B81061,4 Centurion Way,Brough,NaN,NaN,NaN,HU15 1AY
4,336384.0,408 706 2473,658357,Westerby,Heather,06 Nov 1981 12:00,Female,syed_shah_,Dr Syed Shah,RAE,...,M,02/03/1982,✅,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,336385.0,604 889 8681,1342615,Sassen,Nathan Aiyna,13 Aug 1975 12:00,Male,benjamin_teng_7043270,Dr Benjamin Teng,R0A,...,F,27/04/1947,NaN,A81027,1 WORSALL ROAD,Yarm,NaN,NaN,NaN,TS15 9DD
6,334467.0,442 080 0666,RMC00177314,Scholes,June,21 Jun 1943 12:00,Female,Rajesh_Yadavilli_6067675,Dr Rajesh Yadavilli,RMC,...,M,22/03/1965,NaN,A89025,WASHINGTON CENTRE,WASHINGTON,NaN,NaN,NaN,NE38 7NQ
7,336389.0,408 785 9169,336577,Lambert-Cundall,Linda,24 Oct 1966 12:00,Female,generic_email_contact,Lung Cancer Nurses - Bradford,RAE,...,F,27/12/1993,NaN,A83011,26 GILESGATE,DURHAM,NaN,NaN,NaN,DH1 1QW
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,20/09/1942,NaN,B83055,COUSEN ROAD,GREAT HORTON,BRADFORD,NaN,NaN,BD7 3JX
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,20/09/2008,NaN,NaN,1 RAVENSFIELD GARDENS,NaN,NaN,EPSOM,SURREY,KT19 0ST
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,21/09/1972,NaN,P84673,Oxford Rd,NaN,NaN,MANCHESTER,NaN,M13 9PL
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,18/06/1942,NaN,N82035,20 Forthlin Road,NaN,NaN,LIVERPOOL,NaN,L18 9TN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27/07/1970,NaN,P81002,Dalton Square,NaN,NaN,NaN,LANCASTER,NaN,LA1 1PJ
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,03/10/1973,NaN,F83004,110 The Queen's Walk,NaN,NaN,LONDON,NaN,SE1 2AA
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,07/09/1999,NaN,M85124,Victoria Square,NaN,NaN,BIRMINGHAM,NaN,B3 3DQ
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,13/10/1999,NaN,Future: W91022 Current: N81082,"Ffordd, Mold Rd",Mold,NaN,WREXHAM,NaN,LL11 2AH
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,05/01/1924,✅,C81010,NaN,NaN,NaN,NaN,NaN,NG10 1NP
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,13/05/1985,NaN,P84673,Victoria Sq,NaN,NaN,BOLTON,NaN,BL1 1RU
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,11/02/1982,NaN,N81027,Town Hall,7 High Street,NaN,CONGLETON,NaN,CW12 1BN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,20/07/1938,✅,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,19/01/1957,NaN,N81087,Apple Market St,NaN,NaN,Northwich,NaN,CW9 5BB
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,01/01/1971,NaN,C81065,Market Place,NaN,NaN,Buxton,NaN,SK17 6EL
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,09/02/2023,NaN,B82045,Market Place,NaN,NaN,Hawes,NaN,DL8 3QN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,07/12/1978,NaN,A82025,9a Lowther St,NaN,NaN,Kendal,NaN,LA9 4DA
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,01/07/1989,NaN,A82038,Townhead House,Brough,Sowerby,KIRKBY STEPHEN,NaN,CA17 4EG
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,14/01/1965,NaN,Y02657,King William Street,NaN,NaN,Blackburn,Lancashire,BB1 7DY
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,18/09/1967,NaN,Y00206,Manchester Road,NaN,NaN,Burnley,Lancashire,BB11 9SA
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,27/07/1960,NaN,P89020,Stockport Road,NaN,NaN,Tameside,NaN,OL7 0NS
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,F,16/01/1982,NaN,NaN,J B Russell House,Gartnavel Royal Hospital Campus,1055 Great Western Road,Glasgow,NaN,G12 0XH
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,M,29/05/1992,✅ 2025-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN