# dWGS — Part 8: Data Requirements (NEY GMS → NW GMS, RGL to SGL)

NHS England is transitioning centralised Whole Genome Sequencing (WGS) to a distributed
model (dWGS): each NHS GMS geography's **Requesting Genomic Laboratory (RGL)** submits
DNA samples directly to a **Sequencing Genomic Laboratory (SGL)**. This notebook covers
a specific subcontracted arrangement: **North East and Yorkshire GMS acting as RGL**,
submitting samples and a digital manifest to **NW GMS acting as SGL**, whose inbound
order pathway is the same NW Regional Integration Engine (RIE) → iGene ORM^O01
interface `03`-`07` already work with.

Three source documents define the requirement (all in `NotGit/`, gitignored per this
repo's convention, referenced here by name only):

- **`RGL to SGL SOP v0.4.docx`** — NHS England's SOP; Appendix 3 defines the 37-column
  national Digital Manifest CSV.
- **`dWGS Manifest CSV to HL7v2 ORM Transformation Specification v0.1.docx`** — NW GMS's
  draft spec turning that manifest into an ORM^O01 message, plus a 5-column local
  extension NEY GMS adds for NW GMS's benefit.
- **`dWGS Sample Manifest HL7v2 Data Mapping v0.1.xlsx`** — the field-by-field working
  sheet those tables were drawn from.

This is a preparation notebook: the sample data (`Input/dWGS.csv`) and the three-way
field mapping below.

## Where this sits: from clinical order to sequencing result

This notebook's `LAB-35` sub-order is one hop in a longer chain that starts and ends
with the referring clinician. Mapped onto [NW-GMSA's Inter-Laboratory Workflow
(ILW)](https://nw-gmsa.github.io/en/ILW.html#sub-orders-lab-35-and-lab-36) actors:

| Role (ILW) | Party here | Transaction it sends |
|---|---|---|
| Order Placer | Test Ordering Entity (referring Trust/clinician) | `LAB-1` |
| Order Filler | Requesting Genomic Laboratory (RGL) | `LAB-35` (as sub-order placer), `LAB-3` |
| Sub Contractor | Sequencing Genomic Laboratory (SGL) | `LAB-36` *(Option B, below)* |
| Automation Manager | Genomics England Limited (GEL) | `LAB-5` *(Option A, below)* |

`LAB-1` (the original clinical order) and `LAB-35` (RGL's sub-order to the SGL) are
settled — that's what this notebook builds. What's still open is how the result of
that sub-order gets back to the RGL, because GEL sits behind the SGL in the physical
pathway (RGL to SGL SOP v0.4, Figure 1) and doesn't map cleanly onto a single ILW role.

### Process flow

![notebook 8 diagram 1](https://mermaid.ink/svg/Zmxvd2NoYXJ0IFRECiAgICBPUFsiT3JkZXIgUGxhY2VyXG5UZXN0IE9yZGVyaW5nIEVudGl0eSJdCiAgICBPRlsiT3JkZXIgRmlsbGVyXG5SZXF1ZXN0aW5nIEdlbm9taWMgTGFib3JhdG9yeSAoUkdMKSJdCgogICAgc3ViZ3JhcGggU0VRWyJTZXF1ZW5jaW5nIl0KICAgICAgICBTQ1siU3ViIENvbnRyYWN0b3JcblNlcXVlbmNpbmcgR2Vub21pYyBMYWJvcmF0b3J5IChTR0wpIl0KICAgICAgICBHRUxbIkdlbm9taWNzIEVuZ2xhbmQgTGltaXRlZFxuKEF1dG9tYXRpb24gTWFuYWdlcikiXQogICAgICAgIFNDIC0tICJwcmVwYXJlZCBzYW1wbGUiIC0tPiBHRUwKICAgIGVuZAoKICAgIE9QIC0tICJMQUItMVxubGFib3JhdG9yeSBvcmRlciIgLS0+IE9GCiAgICBPRiAtLSAiTEFCLTM1XG5zdWItb3JkZXIgKyBtYW5pZmVzdCIgLS0+IFNDCiAgICBHRUwgLS4gIkxBQi01IChPcHRpb24gQSlcbmRpcmVjdCB0byBPcmRlciBGaWxsZXIiIC4tPiBPRgogICAgU0MgLS4gIkxBQi0zNiAoT3B0aW9uIEIpXG52aWEgU3ViIENvbnRyYWN0b3IiIC4tPiBPRgogICAgT0YgLS0gIkxBQi0zXG5sYWJvcmF0b3J5IHJlcG9ydCIgLS0+IE9Q)

<!--
```mermaid
flowchart TD
    OP["Order Placer\nTest Ordering Entity"]
    OF["Order Filler\nRequesting Genomic Laboratory (RGL)"]

    subgraph SEQ["Sequencing"]
        SC["Sub Contractor\nSequencing Genomic Laboratory (SGL)"]
        GEL["Genomics England Limited\n(Automation Manager)"]
        SC -- "prepared sample" --> GEL
    end

    OP -- "LAB-1\nlaboratory order" --> OF
    OF -- "LAB-35\nsub-order + manifest" --> SC
    GEL -. "LAB-5 (Option A)\ndirect to Order Filler" .-> OF
    SC -. "LAB-36 (Option B)\nvia Sub Contractor" .-> OF
    OF -- "LAB-3\nlaboratory report" --> OP
```
-->

### Sequence diagram

![notebook 8 diagram 2](https://mermaid.ink/svg/c2VxdWVuY2VEaWFncmFtCiAgICBhY3RvciBPUCBhcyBPcmRlciBQbGFjZXI8YnIvPihUZXN0IE9yZGVyaW5nIEVudGl0eSkKICAgIHBhcnRpY2lwYW50IE9GIGFzIE9yZGVyIEZpbGxlcjxici8+KFJHTCkKICAgIHBhcnRpY2lwYW50IFNDIGFzIFN1YiBDb250cmFjdG9yPGJyLz4oU0dMKQogICAgcGFydGljaXBhbnQgR0VMIGFzIEdlbm9taWNzIEVuZ2xhbmQgTHRkPGJyLz4oQXV0b21hdGlvbiBNYW5hZ2VyKQoKICAgIE9QLT4+T0Y6IExBQi0xIExhYm9yYXRvcnkgT3JkZXIKICAgIE9GLT4+U0M6IExBQi0zNSBTdWItb3JkZXIgKHNhbXBsZSArIGRpZ2l0YWwgbWFuaWZlc3QpCiAgICBTQy0+PkdFTDogUmF3IGdlbm9taWMgZGF0YSAocG9zdC1zZXF1ZW5jaW5nKQoKICAgIGFsdCBPcHRpb24gQSDigJQgR0VMIGFzIEF1dG9tYXRpb24gTWFuYWdlcgogICAgICAgIEdFTC0+Pk9GOiBMQUItNSBzdHJ1Y3R1cmVkIHJlc3VsdCAoZGlyZWN0IHRvIE9yZGVyIEZpbGxlcikKICAgIGVsc2UgT3B0aW9uIEIg4oCUIHJlc3VsdCByZXR1cm5lZCB2aWEgdGhlIFN1YiBDb250cmFjdG9yCiAgICAgICAgR0VMLT4+U0M6IEFuYWx5c2VkL2ludGVncmF0ZWQgcmVzdWx0CiAgICAgICAgU0MtPj5PRjogTEFCLTM2IFN1Yi1vcmRlciByZXN1bHQKICAgIGVuZAoKICAgIE9GLT4+T1A6IExBQi0zIExhYm9yYXRvcnkgcmVwb3J0)

<!--
```mermaid
sequenceDiagram
    actor OP as Order Placer<br/>(Test Ordering Entity)
    participant OF as Order Filler<br/>(RGL)
    participant SC as Sub Contractor<br/>(SGL)
    participant GEL as Genomics England Ltd<br/>(Automation Manager)

    OP->>OF: LAB-1 Laboratory Order
    OF->>SC: LAB-35 Sub-order (sample + digital manifest)
    SC->>GEL: Raw genomic data (post-sequencing)

    alt Option A — GEL as Automation Manager
        GEL->>OF: LAB-5 structured result (direct to Order Filler)
    else Option B — result returned via the Sub Contractor
        GEL->>SC: Analysed/integrated result
        SC->>OF: LAB-36 Sub-order result
    end

    OF->>OP: LAB-3 Laboratory report
```
-->

The rest of this notebook zooms into the `LAB-35` step: NE&Y Genomics acting as RGL
(the *Order Filler* above, confusingly also acting as *sub-order placer* toward NW
Genomics), and NW Genomics acting as SGL (*Sub Contractor* above). The field mapping,
worked example, and message-exchange sections below are all about that one hop, not
the full pathway shown here.

## Field mapping: CSV → HL7v2 → FHIR

All 44 manifest fields: 37 national, from `RGL to SGL SOP v0.4` Appendix 3, plus the 7 NW
GMS local-extension fields (positions 38-44) from the `dWGS Digital Manifest Requirements
NEY to NW GMS v0.2` and the transformation spec v0.2, Section 7.2.
`Input/dWGS.csv` now holds **only the 37 national columns**. The local-extension rows stay
in the table for their mappings, but their values have to come from somewhere other than
the national manifest - see the `source` column and
[Sample manifest data](#Sample-manifest-data) below. Fields the
transformation spec marks `HL7v2 Mapping Required = FALSE` are left blank in both the
`hl7v2_field` and `fhir_field` columns — they're carried in the CSV but not transmitted
onward.

The `fhir_field` column is this notebook's own addition — neither source document
mentions FHIR. Identifiers/profiles reused from `03`-`07` are shown as-is.
`family_structure` and `participant_type` map to NW-GMSA's
[`FamilyGeneticGroup`](https://nw-gmsa.github.io/en/StructureDefinition-FamilyGeneticGroup.html)
(a FHIR `Group`, not an `Observation`): `family_structure` is `Group.code`
(Singleton/Duo/Trio) and `participant_type` is the patient's
`Group.member.extension:relationship`. `referral_id` identifies that group
(`Group.identifier:ReferralId`, system `https://fhir.nwgenomics.nhs.uk/Identifier/NGIS-ReferralIdentifier`)
as well as being the order's `ServiceRequest.requisition`.

**Two specimens, not one**: the `primary_sample_*` fields describe the specimen as
originally received at the GLH (blood/tissue, before extraction); `dispatched_sample_*`
describes the extracted DNA sent onward. Each is its own `SPM` segment/`Specimen`
resource - the dispatched specimen's `Specimen.parent` would reference the primary
specimen's. `primary_sample_type`'s germline/tumour distinction has no clean SPM/Specimen
field to sit in (HL7v2 has no field for it, and FHIR's closer fit is arguably an
`Observation` component, not `Specimen`) - marked low-confidence rather than guessed.

**GLH codes are not trust codes, or ODS codes**: `ordering_entity_id` is correctly a
referring NHS Trust's ODS code (e.g. `RR8` Leeds Teaching Hospitals) — but
`glh_laboratory_id` is Genomics England's own **short GLH code**, not an ODS code at all.
A real NW GLH manifest export (`ngis_glh_to_gel_sample_sent_now_<timestamp>.csv`, kept in
`NotGit/`) carries `now` for North West in every row, and the data mapping workbook gives
`now` as its example too. `Input/dWGS.csv` uses `yne` for North East and Yorkshire (not
yet confirmed against a real NE&Y export). Wherever FHIR or v2 needs an ODS code (message
sender, requester, identifier assigners), the worked example looks it up from the GLH
code (`GEL_GLH_ODS` below). NE&Y's hub ODS code, confirmed against the live NHS ODS API
(`directory.spineservices.nhs.uk`), is **`699N0`, "YORKSHIRE AND NORTH EAST GLH"**
(Newcastle-based). It's an ODS tier above individual trusts, the same pattern
`02-work-orders-worked-example.ipynb` explains for `699X0`/`K1S6S`, North West's own
hub/site codes. The `Questionnaire-dWGSSubOrder` design note still calls
`glh_laboratory_id` an ODS code, which the real export contradicts.

**Sample type and state are GEL enumerations, not SNOMED CT**: the same real export and
workbook use `primary_sample_type`/`dispatched_sample_type` values such as
`Normal or Germline sample`, `Solid tumour sample` and `Liquid tumour sample`, and
`primary_sample_state` values such as `blood_unsorted_edta` (`dispatched_sample_state` is
`DNA`). The worked example maps `primary_sample_state` onto a SNOMED CT code from
NW-GMSA's specimen-type ValueSet (`PRIMARY_SAMPLE_STATE_SNOMED` below) to build
`Specimen.type`.

In [1]:
import pandas as pd

FIELD_MAPPING = [
    # csv_field, common_name, cardinality, field_type, hl7v2_field, fhir_field
    # cardinality/field_type source: RGL to SGL SOP v0.4 Appendix 3 (national fields) and the
    # transformation spec v0.2 Section 7.2 (NW GMS local-extension fields, positions 38-44) - in
    # manifest column order. Input/dWGS.csv carries only the first 37 (national) of these.
    ("referral_id", "Original Order Placer Group Number", "MUST", "String",
     "ORC-4 Placer Group Number (ORC-4.2 = 8J834) + OBX-5 (OBX-3=NGIS_REFERRAL_ID)",
     "ServiceRequest.requisition (NGISReferralId) + Group.identifier:ReferralId"),
    ("clinical_indication_test_type_id", "Test Code", "OPTIONAL", "String",
     "OBR-4.1", "ServiceRequest.code.coding (England-GenomicTestDirectory)"),
    ("patient_nhs_number", "NHS Number", "OPTIONAL", "String",
     "PID-3 (NH)", "Patient.identifier (NHS number)"),
    ("patient_ngis_id", "Patient Identifier", "MUST", "String",
     "PID-3 (PID-3.4 = 8J834, PID-3.5 = PI)",
     "Patient.identifier (PI, assigner Genomics England 8J834)"),
    ("patient_date_of_birth", "Date Of Birth", "OPTIONAL", "Date",
     "PID-7.1", "Patient.birthDate"),
    ("ordering_entity_id", "Original Ordering Facility Code", "OPTIONAL", "Code (ODS Code)",
     "ORC-21", "Specimen.identifier (as received) assigner"),
    ("glh_laboratory_id", "Filler Order Ordering Facility Code", "MUST", "Code (GEL GLH short code, e.g. now/yne)",
     "ORC-21 (ODS code via GEL_GLH_ODS)", "(ODS code via GEL_GLH_ODS) ServiceRequest.requester (PractitionerRole.organization when approved_by is present) / Specimen.identifier (LIMS) assigner"),
    ("primary_sample_received_date", "Sample Received Date", "OPTIONAL", "Date",
     "SPM-18 (primary SPM)", "Specimen.receivedTime (primary specimen)"),
    ("primary_sample_id_as_received_by_glh", "Received Sample Identifier", "OPTIONAL", "String",
     "SPM-2.1 (primary SPM)", "Specimen.identifier (as received)"),
    ("primary_sample_id_in_glh_lims", "LIMS Sample Identifier", "OPTIONAL", "String",
     "SPM-2.2 (primary SPM)", "Specimen.identifier (GLH LIMS)"),
    ("primary_sample_type", "Sample Type", "MUST", "Enum (e.g. Normal or Germline sample)",
     "SPM-11 (primary SPM, low confidence)", "Specimen.type / extension (germline vs tumour, low confidence)"),
    ("primary_sample_state", "Sample Material Type", "MUST", "Enum (e.g. blood_unsorted_edta)",
     "SPM-4.1 (primary SPM, SNOMED CT via PRIMARY_SAMPLE_STATE_SNOMED)",
     "Specimen.type (SNOMED CT coding via PRIMARY_SAMPLE_STATE_SNOMED)"),
    ("received_sample_topography", "Sample Topography", "MUST (cancer only)", "String",
     "SPM-8 (primary SPM, cancer only)", "Specimen.bodySite (cancer only)"),
    ("received_sample_morphology", "Sample Morphology", "OPTIONAL", "String", "", ""),
    ("received_sample_tumour_content_%", "Tumour Content", "MUST (cancer only)", "Number", "", ""),
    ("received_sample_comments", "Sample Comments", "OPTIONAL", "String", "", ""),
    ("received_sample_collection_date", "Specimen Collection Date", "OPTIONAL", "Date", "", ""),
    ("dispatched_sample_id_in_glh_lims", "Dispatched Sample Identifier", "OPTIONAL", "String", "", ""),
    ("dispatched_sample_lsid", "Specimen Barcode", "MUST", "String",
     "ORC-2.1/OBR-2.1 Placer Order Number (assigning authority = sending GLH ODS) + SPM-2.1 (type=ZCID) + OBX-5 (OBX-3=DISPATCHED_SAMPLE_LSID)",
     "ServiceRequest.identifier:OrderIdentifier (PLAC, assigner = sending GLH ODS) + Specimen.container.identifier"),
    ("dispatched_sample_type", "Dispatched Sample Type", "MUST", "Enum (e.g. Normal or Germline sample)", "", ""),
    ("dispatched_sample_state", "Dispatched Material Type", "MUST", "Enum (DNA)",
     "SPM-4.1 (dispatched SPM, not built in this worked example)",
     "Specimen.type (not built - single Specimen only carries primary_sample_state)"),
    ("dispatched_sample_volume_(ul)", "Sample Volume", "OPTIONAL", "Number",
     "SPM-12", "Specimen.collection.quantity"),
    ("laboratory_remaining_volume_banked_(ul)", "Remaining Banked Volume", "OPTIONAL", "Number", "", ""),
    ("glh_concentration_(ng/ul)", "DNA Concentration", "OPTIONAL", "Number", "", ""),
    ("glh_od260/280", "DNA Purity", "OPTIONAL", "Number", "", ""),
    ("glh_din_value", "DNA Integrity Number", "OPTIONAL", "Number", "", ""),
    ("glh_percentage_DNA_over_23kb", "DNA Fragment Size", "OPTIONAL", "Number", "", ""),
    ("glh_qc_status", "QC Status", "OPTIONAL", "String", "", ""),
    ("glh_sample_dispatch_date", "Dispatch Date", "OPTIONAL", "Date", "", ""),
    ("glh_sample_consignment_number", "Consignment Number", "OPTIONAL", "String",
     "SPM-32", "Specimen.identifier (type=STN)"),
    ("plating_organisation", "Plating Organisation", "OPTIONAL", "Enum", "", ""),
    ("gmc_rack_id", "Rack Identifier", "OPTIONAL", "String", "", ""),
    ("gmc_rack_well", "Rack Well Position", "OPTIONAL", "String (pattern)", "", ""),
    ("dna_extraction_protocol", "DNA Extraction Method", "OPTIONAL", "String",
     "SPM-7", "Specimen.collection.method"),
    ("prolonged_sample_storage", "Sample Storage Method", "OPTIONAL", "String", "", ""),
    ("retrospective_sample", "Retrospective Sample Flag", "OPTIONAL", "Enum",
     "(no clean v2 field)", "ServiceRequest.intent (reflex-order when Retrospective)"),
    ("approved_by", "Approved By", "OPTIONAL", "String", "",
     "ServiceRequest.requester -> PractitionerRole.practitioner.display (when present)"),
    ("placer_order_number", "Placer Order Number", "MUST", "String",
     "ORC-2.1 / OBR-2.1", "ServiceRequest.identifier:OrderIdentifier (PLAC) - built from dispatched_sample_lsid"),
    ("patient_forename", "Forename", "MUST", "String", "PID-5.2", "Patient.name.given"),
    ("patient_surname", "Surname", "MUST", "String", "PID-5.1", "Patient.name.family"),
    ("patient_medical_record_number", "Medical Record Number", "MUST", "String",
     "PID-3 (MR)", "Patient.identifier (MR) (not built - no source yet)"),
    ("family_structure", "Family Structure", "MUST", "Enumerated string",
     "OBX-5 (OBX-3=FAMILY_STRUCTURE)", "Group.code (FamilyGeneticGroup, FamilyStructure ValueSet)"),
    ("participant_type", "Participant Type", "MUST", "Enumerated string",
     "OBX-5 (OBX-3=PARTICIPANT_TYPE)", "Group.member.extension:relationship (FamilyGeneticGroup)"),
    ("clinical_information", "Clinical Information", "OPTIONAL", "String", "NTE-3", "ServiceRequest.note"),
]

field_mapping_df = pd.DataFrame(
    FIELD_MAPPING,
    columns=["csv_field", "common_name", "cardinality", "field_type", "hl7v2_field", "fhir_field"],
)

# Positions 38-44: NW GMS asked for these; they're not in the national manifest (or Input/dWGS.csv).
LOCAL_EXTENSION_SOURCE = {
    "placer_order_number": "dispatched_sample_lsid (proposed - nw-gmsa-use-cases dWGS.md)",
    "patient_forename": "local extension - NHS England PDS (by NHS number)",
    "patient_surname": "local extension - NHS England PDS (by NHS number)",
    "patient_medical_record_number": "local extension - sending trust (not in PDS; TBC)",
    "family_structure": "local extension - TBC (stand-in below)",
    "participant_type": "local extension - TBC (stand-in below)",
    "clinical_information": "local extension - TBC (stand-in below)",
}
field_mapping_df["source"] = field_mapping_df.csv_field.map(LOCAL_EXTENSION_SOURCE).fillna("national manifest (Input/dWGS.csv)")
national_fields = field_mapping_df[~field_mapping_df.csv_field.isin(LOCAL_EXTENSION_SOURCE)].csv_field.tolist()
assert len(national_fields) == 37 and field_mapping_df.csv_field.tolist()[37:] == list(LOCAL_EXTENSION_SOURCE)
field_mapping_df

,csv_field,common_name,cardinality,field_type,hl7v2_field,fhir_field,source
0,referral_id,Original Order Placer Group Number,MUST,String,ORC-4 Placer Group Number (ORC-4.2 = 8J834) + ...,ServiceRequest.requisition (NGISReferralId) + ...,national manifest (Input/dWGS.csv)
1,clinical_indication_test_type_id,Test Code,OPTIONAL,String,OBR-4.1,ServiceRequest.code.coding (England-GenomicTes...,national manifest (Input/dWGS.csv)
2,patient_nhs_number,NHS Number,OPTIONAL,String,PID-3 (NH),Patient.identifier (NHS number),national manifest (Input/dWGS.csv)
3,patient_ngis_id,Patient Identifier,MUST,String,"PID-3 (PID-3.4 = 8J834, PID-3.5 = PI)","Patient.identifier (PI, assigner Genomics Engl...",national manifest (Input/dWGS.csv)
4,patient_date_of_birth,Date Of Birth,OPTIONAL,Date,PID-7.1,Patient.birthDate,national manifest (Input/dWGS.csv)
5,ordering_entity_id,Original Ordering Facility Code,OPTIONAL,Code (ODS Code),ORC-21,Specimen.identifier (as received) assigner,national manifest (Input/dWGS.csv)
6,glh_laboratory_id,Filler Order Ordering Facility Code,MUST,"Code (GEL GLH short code, e.g. now/yne)",ORC-21 (ODS code via GEL_GLH_ODS),(ODS code via GEL_GLH_ODS) ServiceRequest.requ...,national manifest (Input/dWGS.csv)
7,primary_sample_received_date,Sample Received Date,OPTIONAL,Date,SPM-18 (primary SPM),Specimen.receivedTime (primary specimen),national manifest (Input/dWGS.csv)
8,primary_sample_id_as_received_by_glh,Received Sample Identifier,OPTIONAL,String,SPM-2.1 (primary SPM),Specimen.identifier (as received),national manifest (Input/dWGS.csv)
9,primary_sample_id_in_glh_lims,LIMS Sample Identifier,OPTIONAL,String,SPM-2.2 (primary SPM),Specimen.identifier (GLH LIMS),national manifest (Input/dWGS.csv)
10,primary_sample_type,Sample Type,MUST,Enum (e.g. Normal or Germline sample),"SPM-11 (primary SPM, low confidence)","Specimen.type / extension (germline vs tumour,...",national manifest (Input/dWGS.csv)
11,primary_sample_state,Sample Material Type,MUST,Enum (e.g. blood_unsorted_edta),"SPM-4.1 (primary SPM, SNOMED CT via PRIMARY_SA...",Specimen.type (SNOMED CT coding via PRIMARY_SA...,national manifest (Input/dWGS.csv)
12,received_sample_topography,Sample Topography,MUST (cancer only),String,"SPM-8 (primary SPM, cancer only)",Specimen.bodySite (cancer only),national manifest (Input/dWGS.csv)
13,received_sample_morphology,Sample Morphology,OPTIONAL,String,,,national manifest (Input/dWGS.csv)
14,received_sample_tumour_content_%,Tumour Content,MUST (cancer only),Number,,,national manifest (Input/dWGS.csv)
15,received_sample_comments,Sample Comments,OPTIONAL,String,,,national manifest (Input/dWGS.csv)
16,received_sample_collection_date,Specimen Collection Date,OPTIONAL,Date,,,national manifest (Input/dWGS.csv)
17,dispatched_sample_id_in_glh_lims,Dispatched Sample Identifier,OPTIONAL,String,,,national manifest (Input/dWGS.csv)
18,dispatched_sample_lsid,Specimen Barcode,MUST,String,ORC-2.1/OBR-2.1 Placer Order Number (assigning...,ServiceRequest.identifier:OrderIdentifier (PLA...,national manifest (Input/dWGS.csv)
19,dispatched_sample_type,Dispatched Sample Type,MUST,Enum (e.g. Normal or Germline sample),,,national manifest (Input/dWGS.csv)
20,dispatched_sample_state,Dispatched Material Type,MUST,Enum (DNA),"SPM-4.1 (dispatched SPM, not built in this wor...",Specimen.type (not built - single Specimen onl...,national manifest (Input/dWGS.csv)
21,dispatched_sample_volume_(ul),Sample Volume,OPTIONAL,Number,SPM-12,Specimen.collection.quantity,national manifest (Input/dWGS.csv)
22,laboratory_remaining_volume_banked_(ul),Remaining Banked Volume,OPTIONAL,Number,,,national manifest (Input/dWGS.csv)
23,glh_concentration_(ng/ul),DNA Concentration,OPTIONAL,Number,,,national manifest (Input/dWGS.csv)
24,glh_od260/280,DNA Purity,OPTIONAL,Number,,,national manifest (Input/dWGS.csv)
25,glh_din_value,DNA Integrity Number,OPTIONAL,Number,,,national manifest (Input/dWGS.csv)
26,glh_percentage_DNA_over_23kb,DNA Fragment Size,OPTIONAL,Number,,,national manifest (Input/dWGS.csv)
27,glh_qc_status,QC Status,OPTIONAL,String,,,national manifest (Input/dWGS.csv)
28,glh_sample_dispatch_date,Dispatch Date,OPTIONAL,Date,,,national manifest (Input/dWGS.csv)
29,glh_sample_consignment_number,Consignment Number,OPTIONAL,String,SPM-32,Specimen.identifier (type=STN),national manifest (Input/dWGS.csv)
30,plating_organisation,Plating Organisation,OPTIONAL,Enum,,,national manifest (Input/dWGS.csv)
31,gmc_rack_id,Rack Identifier,OPTIONAL,String,,,national manifest (Input/dWGS.csv)
32,gmc_rack_well,Rack Well Position,OPTIONAL,String (pattern),,,national manifest (Input/dWGS.csv)
33,dna_extraction_protocol,DNA Extraction Method,OPTIONAL,String,SPM-7,Specimen.collection.method,national manifest (Input/dWGS.csv)
34,prolonged_sample_storage,Sample Storage Method,OPTIONAL,String,,,national manifest (Input/dWGS.csv)
35,retrospective_sample,Retrospective Sample Flag,OPTIONAL,Enum,(no clean v2 field),ServiceRequest.intent (reflex-order when Retro...,national manifest (Input/dWGS.csv)
36,approved_by,Approved By,OPTIONAL,String,,ServiceRequest.requester -> PractitionerRole.p...,national manifest (Input/dWGS.csv)
37,placer_order_number,Placer Order Number,MUST,String,ORC-2.1 / OBR-2.1,ServiceRequest.identifier:OrderIdentifier (PLA...,dispatched_sample_lsid (proposed - nw-gmsa-use...
38,patient_forename,Forename,MUST,String,PID-5.2,Patient.name.given,local extension - NHS England PDS (by NHS number)
39,patient_surname,Surname,MUST,String,PID-5.1,Patient.name.family,local extension - NHS England PDS (by NHS number)
40,patient_medical_record_number,Medical Record Number,MUST,String,PID-3 (MR),Patient.identifier (MR) (not built - no source...,local extension - sending trust (not in PDS; TBC)
41,family_structure,Family Structure,MUST,Enumerated string,OBX-5 (OBX-3=FAMILY_STRUCTURE),"Group.code (FamilyGeneticGroup, FamilyStructur...",local extension - TBC (stand-in below)
42,participant_type,Participant Type,MUST,Enumerated string,OBX-5 (OBX-3=PARTICIPANT_TYPE),Group.member.extension:relationship (FamilyGen...,local extension - TBC (stand-in below)
43,clinical_information,Clinical Information,OPTIONAL,String,NTE-3,ServiceRequest.note,local extension - TBC (stand-in below)

## Sample manifest data

`Input/dWGS.csv` is the **37-column national manifest only**. It's checked against the
national rows of the mapping table above: every `MUST`/`MUST (cancer only)` field is
populated, and the type-sensitive fields (`Number`, `Date`, `String (pattern)`) parse
cleanly.

### Missing local-extension fields need another source

The 7 NW GMS local-extension columns aren't in the national manifest, so this worked
example can't read them from `Input/dWGS.csv`. That's by design rather than an oversight: the
SOP (v0.4, "Sample Manifest" under Section 4) states that *"Patient identifiable information
will not be included, either within the consignment documentation or in any external or
internal communications"*. Each missing field needs its own source:

- **Patient demographics (`patient_forename`, `patient_surname`)** - most likely
  **NHS England PDS** (Personal Demographics Service), looked up by `patient_nhs_number`,
  which *is* in the national manifest. This repo already uses PDS: `Input/PDS/NEY.csv` and
  `Input/PDS/NW.csv` are extracts of NHS England's PDS integration-environment test
  patients. The worked example below looks the name up there, and checks the date of birth
  against the manifest's `patient_date_of_birth`, in place of a live PDS (FHIR API) query. Not
  every `Input/dWGS.csv` patient is in those extracts: the `9999999…` EDI test patients
  would need a live PDS integration-environment lookup.
- **`patient_medical_record_number`** - **not** available from PDS. PDS holds national
  demographics, not a trust's local hospital number. It has to come from the sending
  organisation (the spec's own open question: *"Confirm the NEY source, format and
  assigning authority for patient_medical_record_number"*). It isn't built below.
- **`placer_order_number`** - taken from `dispatched_sample_lsid`, which *is* in the
  national manifest. `referral_id` and `patient_ngis_id` aren't unique per order (a family,
  or a cancer referral's germline and tumour samples, share them), but the LSID is unique
  per dispatched tube. The NW-GMSA use cases `dWGS.md` proposes this ("placer_order_number:
  use the LSID", under Outstanding Issues). See the ServiceRequest section.
- **`family_structure`, `participant_type`, `clinical_information`** - not demographics,
  so PDS doesn't help; their source is still to be agreed. The worked example uses
  clearly-labelled stand-in values (the ones `Input/dWGS.csv` carried before its local
  columns were removed) so the `FamilyGeneticGroup` and `ServiceRequest.note` can still
  be built.

In [2]:
dwgs_df = pd.read_csv("Input/dWGS.csv", dtype=str, keep_default_na=False)
print(f"{len(dwgs_df)} rows, {len(dwgs_df.columns)} columns")

assert list(dwgs_df.columns) == national_fields, \
    "Input/dWGS.csv must be exactly the 37 national manifest columns, in the field mapping table's order"
national_mapping_df = field_mapping_df[field_mapping_df.csv_field.isin(national_fields)]

# Unconditional MUST fields must not be blank. "MUST (cancer only)" fields are
# conditional and not checked here - the cancer (M-code) rows leave topography and
# tumour content blank, exactly as a real GLH manifest export does.
must_fields = national_mapping_df[national_mapping_df.cardinality == "MUST"].csv_field
for field in must_fields:
    blank_rows = dwgs_df.index[dwgs_df[field].str.strip() == ""].tolist()
    assert not blank_rows, f"{field} is MUST but blank in row(s) {blank_rows}"

# Number/Date fields must parse as their stated type.
for field in national_mapping_df[national_mapping_df.field_type == "Number"].csv_field:
    dwgs_df[field].map(lambda v: float(v) if v.strip() else None)
for field in national_mapping_df[national_mapping_df.field_type == "Date"].csv_field:
    pd.to_datetime(dwgs_df[field].replace("", pd.NaT))

# gmc_rack_well must match the SOP's stated pattern.
rack_well_pattern = r"^[A-H][0][1-9]|[A-H][1][0-2]$"
assert dwgs_df.gmc_rack_well.str.match(rack_well_pattern).all(), "gmc_rack_well values must match the SOP pattern"

# Enumerated values seen in a real GLH manifest export and the data mapping workbook.
SAMPLE_TYPES = {"Normal or Germline sample", "Solid tumour sample", "Liquid tumour sample"}
for field in ("primary_sample_type", "dispatched_sample_type"):
    assert dwgs_df[field].isin(SAMPLE_TYPES).all(), f"{field} must be one of {SAMPLE_TYPES}"
assert (dwgs_df.dispatched_sample_state == "DNA").all(), "dispatched_sample_state is expected to be DNA for dWGS"

print("Input/dWGS.csv satisfies every national cardinality/field_type constraint above.")
dwgs_df

11 rows, 37 columns
Input/dWGS.csv satisfies every national cardinality/field_type constraint above.

,referral_id,clinical_indication_test_type_id,patient_nhs_number,patient_ngis_id,patient_date_of_birth,ordering_entity_id,glh_laboratory_id,primary_sample_received_date,primary_sample_id_as_received_by_glh,primary_sample_id_in_glh_lims,...,glh_qc_status,glh_sample_dispatch_date,glh_sample_consignment_number,plating_organisation,gmc_rack_id,gmc_rack_well,dna_extraction_protocol,prolonged_sample_storage,retrospective_sample,approved_by
0,r26000000201,R14.1,9737383222,p26000000101,1978-01-17,RR8,yne,2026-08-20,S26-1A01,S26-1A01,...,Pass,2026-08-26,NEY GLH 2026-08-26,wwm,FK00000001,A01,,,New,Duty Scientist on behalf of NEYGLH Medical
1,r26000000202,R59.1,9737873971,p26000000102,1947-04-27,RTR,yne,2026-08-20,S26-1A02,S26-1A02,...,Pass,2026-08-26,NEY GLH 2026-08-26,wwm,FK00000001,A02,,,New,Duty Scientist on behalf of NEYGLH Medical
2,r26000000202,R59.1,9999999603,p26000000103,1984-11-06,RTR,yne,2026-08-20,S26-1A03,S26-1A03,...,Pass,2026-08-26,NEY GLH 2026-08-26,wwm,FK00000001,A03,,,New,Duty Scientist on behalf of NEYGLH Medical
3,r26000000203,R27.3,9737383362,p26000000104,1989-07-01,RNN,yne,2026-08-20,S26-1A04,S26-1A04,...,Pass,2026-08-26,NEY GLH 2026-08-26,wwm,FK00000001,A04,,,New,Duty Scientist on behalf of NEYGLH Medical
4,r26000000203,R27.3,9999999581,p26000000105,1960-01-01,RNN,yne,2026-08-20,S26-1A05,S26-1A05,...,Pass,2026-08-26,NEY GLH 2026-08-26,wwm,FK00000001,A05,,,New,Duty Scientist on behalf of NEYGLH Medical
5,r26000000203,R27.3,9999999514,p26000000106,1988-01-14,RNN,yne,2026-08-20,S26-1A06,S26-1A06,...,Pass,2026-08-26,NEY GLH 2026-08-26,wwm,FK00000001,A06,,,New,Duty Scientist on behalf of NEYGLH Medical
6,r26000000204,R27.3,9737873866,p26000000107,1982-03-02,,yne,2026-09-28,S26-1A07,S26-1A07,...,Pass,2026-10-05,NEY GLH 2026-10-05,wwm,FK00000002,A07,,,New,Duty Scientist on behalf of NEYGLH Medical
7,r26000000205,M27.16,9737873874,p26000000108,1965-03-22,,yne,2026-09-25,S26-1A08,S26-1A08,...,Pass,2026-10-05,NEY GLH 2026-10-05,wwm,FK00000002,A08,,,New,Duty Scientist on behalf of NEYGLH Medical
8,r26000000205,M27.16,9737873874,p26000000108,1965-03-22,,yne,2026-09-25,S26-1A09,S26-1A09,...,Pass,2026-10-05,NEY GLH 2026-10-05,wwm,FK00000002,A09,,,New,Duty Scientist on behalf of NEYGLH Medical
9,r26000000206,M91.1,9737873998,p26000000109,1993-12-27,,yne,2026-09-30,S26-1A10,S26-1A10,...,Pass,2026-10-05,NEY GLH 2026-10-05,wwm,FK00000002,A10,,,New,Duty Scientist on behalf of NEYGLH Medical
10,r26000000206,M91.1,9737873998,p26000000109,1993-12-27,,yne,2026-09-30,S26-1A11,S26-1A11,...,Pass,2026-10-05,NEY GLH 2026-10-05,wwm,FK00000002,A11,,,New,Duty Scientist on behalf of NEYGLH Medical

## Background

`Input/dWGS.csv` is a convenient stand-in, not a claim about the real world: in practice
each GLH/LIMS combination is likely to export a different local format, and this
notebook's manifest is only one plausible shape used here to get test data flowing
end-to-end. The field mapping above is the part expected to generalise; the CSV's exact
column names are not.

### Where this sits: a sub-contracted order

At a high level, North East and Yorkshire (NE&Y) Genomics referring a sample on to North
West Genomics for sequencing is a **sub-contracted order**. In NW-GMSA's own
[Inter-Laboratory Workflow (ILW) page](https://nw-gmsa.github.io/en/ILW.html), this is
**`LAB-35`** (Sub-order Management) — a laboratory (NE&Y Genomics, acting as an *Order
Placer* toward NW Genomics) sending a sub-order to another laboratory (NW Genomics,
acting as *Order Filler*) for testing it can't do itself, distinct from `LAB-1` (the
original clinical order a referring Trust placed with NE&Y Genomics in the first place).
Results come back the same way, as `LAB-36`.

Per [NW-GMSA's Message Exchange page](https://nw-gmsa.github.io/en/MQ.html), a `LAB-35`
order like this can be sent as **either** a FHIR `Bundle` (`POST [base]/$process-message`,
the [laboratory-order `MessageDefinition`](MessageDefinition-laboratory-order.html)) or
HL7 v2 `OML^O21` (MLLP, [documented here](hl7v2.html#oml_o21-laboratory-order)) — the
same choice `03-laboratory-order-from-csv.ipynb` exercised for a different kind of
order. Both follow the *same* underlying data model (next section), so the choice is
purely about what the sending system can produce.

### Why the format actually sent will vary

Which format NE&Y Genomics uses will depend on how each constituent lab implements it.
"NE&Y Genomics" isn't one building — the
[Yorkshire and North East GLH](https://directory.spineservices.nhs.uk/ORD/2-0-0/organisations/699N0)
is a partnership of laboratories. The manifest's `glh_laboratory_id` only identifies the
GLH as a whole (`yne`), not which of these constituent labs handled the sample. Their ODS
codes, confirmed against the live
[NHS ODS API](https://directory.spineservices.nhs.uk/ORD/2-0-0/organisations), are:

- **Northern Genetics Service**, Newcastle — `699N0` (the GLH's own registration,
  based at Newcastle's Institute for Human Genetics - not `RTD07`, that site's separate
  NHS Trust Site identity, which this manifest field doesn't use)
- **Sheffield Diagnostic Genetics Service** — `699D0`
- **The Leeds Genetics Laboratory** — `699C0`

Some of these may already run a LIMS capable of sending `ORM^O01`/`OML^O21` (or FHIR)
directly; others may only export a flat file, needing a data pipeline in between to
produce a proper order message. `Input/dWGS.csv` is standing in for that second case.

![notebook 8 diagram 3](https://mermaid.ink/svg/Zmxvd2NoYXJ0IFRCCiAgICBzdWJncmFwaCBHTEhbIk5FJlkgR2Vub21pY3MiXQogICAgICAgIE5DTFsiTm9ydGhlcm4gR2VuZXRpY3MgU2VydmljZTxici8+TmV3Y2FzdGxlIC0gNjk5TjAiXQogICAgICAgIFNIRlsiU2hlZmZpZWxkIERpYWdub3N0aWM8YnIvPkdlbmV0aWNzIFNlcnZpY2UgLSA2OTlEMCJdCiAgICAgICAgTERTWyJUaGUgTGVlZHMgR2VuZXRpY3M8YnIvPkxhYm9yYXRvcnkgLSA2OTlDMCJdCiAgICBlbmQKICAgIFBJUEVbIk1hbmlmZXN0IENTViAtPiBtZXNzYWdlPGJyLz5kYXRhIHBpcGVsaW5lPGJyLz4odGhpcyBub3RlYm9vaydzIHdvcmtlZCBleGFtcGxlKSJdCiAgICBSSUVbIk5XIEdlbm9taWNzPGJyLz5SZWdpb25hbCBJbnRlZ3JhdGlvbiBFbmdpbmUgKFJJRSk8YnIvPjY5OVgwIl0KCiAgICBOQ0wgLS0gIkxJTVMgc2VuZHMgT01MXk8yMSAvIE8yMSBGSElSIE1lc3NhZ2UgZGlyZWN0bHkiIC0tPiBSSUUKICAgIExEUyAtLSAiTElNUyBzZW5kcyBPTUxeTzIxIC8gTzIxIEZISVIgTWVzc2FnZSBkaXJlY3RseSIgLS0+IFJJRQogICAgU0hGIC0tICJMSU1TIGV4cG9ydHMgYSBtYW5pZmVzdCBDU1YiIC0tPiBQSVBFCiAgICBQSVBFIC0tICJPTUxeTzIxIC8gTzIxIEZISVIgTWVzc2FnZSIgLS0+IFJJRQ==)

<!--
```mermaid
flowchart TB
    subgraph GLH["NE&Y Genomics"]
        NCL["Northern Genetics Service<br/>Newcastle - 699N0"]
        SHF["Sheffield Diagnostic<br/>Genetics Service - 699D0"]
        LDS["The Leeds Genetics<br/>Laboratory - 699C0"]
    end
    PIPE["Manifest CSV -> message<br/>data pipeline<br/>(this notebook's worked example)"]
    RIE["NW Genomics<br/>Regional Integration Engine (RIE)<br/>699X0"]

    NCL -- "LIMS sends OML^O21 / O21 FHIR Message directly" --> RIE
    LDS -- "LIMS sends OML^O21 / O21 FHIR Message directly" --> RIE
    SHF -- "LIMS exports a manifest CSV" --> PIPE
    PIPE -- "OML^O21 / O21 FHIR Message" --> RIE
```
-->

### The shared data model

Both the v2 and FHIR `O21` orders follow the same model, defined once in the NW
Implementation Guide and rendered as whichever wire format the sender chooses:

![notebook 8 diagram 4](https://mermaid.ink/svg/ZXJEaWFncmFtCiAgICBNZXNzYWdlSGVhZGVyIHx8LS18fCBTZXJ2aWNlUmVxdWVzdCA6IGZvY3VzCiAgICBQYXRpZW50IHx8LS1veyBTZXJ2aWNlUmVxdWVzdCA6IHN1YmplY3QKICAgIFNlcnZpY2VSZXF1ZXN0IHx8LS1veyBTcGVjaW1lbiA6IHNwZWNpbWVuCiAgICBTZXJ2aWNlUmVxdWVzdCB9by0tb3wgRmFtaWx5R2VuZXRpY0dyb3VwIDogc3VwcG9ydGluZ0luZm8KICAgIEZhbWlseUdlbmV0aWNHcm91cCB8fC0tfHsgUGF0aWVudCA6IG1lbWJlcg==)

<!--
```mermaid
erDiagram
    MessageHeader ||--|| ServiceRequest : focus
    Patient ||--o{ ServiceRequest : subject
    ServiceRequest ||--o{ Specimen : specimen
    ServiceRequest }o--o| FamilyGeneticGroup : supportingInfo
    FamilyGeneticGroup ||--|{ Patient : member
```
-->

- **`MessageHeader`** (`MSH`)
- **`Patient`** (`PID`)
- **`ServiceRequest`** (`ORC` + `OBR`)
- **`Specimen`** (`SPM`)
- **`Group`** ([`FamilyGeneticGroup`](https://nw-gmsa.github.io/en/StructureDefinition-FamilyGeneticGroup.html))
  — the family (pedigree) this patient is tested with: Singleton, Duo or Trio
  (`family_structure`), and this patient's role in it (`participant_type`). Earlier
  passes of this notebook carried both as "ask at order" `Observation`s via
  `ServiceRequest.supportingInfo`; the IG now models them as a `Group` instead, still
  referenced from `ServiceRequest.supportingInfo` (its `familyGeneticGroup` slice). The
  `Group` is identified by the `referral_id`, the same value each family member's
  `ServiceRequest.requisition` (Order Group Number, `ORC-4`) carries, so the order
  points at its family both by reference and by that shared identifier. Each family
  member is still ordered in a separate message, but because the manifest is a CSV
  listing every participant, each message's `Group` can list the **whole family**.
  The CSV rows sharing that `referral_id` are the family. The message's own patient is
  referenced by `fullUrl`, and the other family members (whose `Patient` resources
  travel in their own messages) are referenced by NHS number.

**NW Genomics' own LIMS speaks HL7 v2 internally, always** — regardless of which format
this sub-order arrives in, the RIE is what transforms it (FHIR or v2) into NW Genomics'
internal v2 shape before it ever reaches the LIMS. The worked example below builds the
external-facing FHIR order and converts it to v2 the same way the RIE's own
`transformToV2` tooling does — it does not reach into the LIMS's internal format.

### Room to extend beyond what's specified

Although the NW data model above names specific FHIR and v2 elements, it doesn't forbid
others - both standards still accept elements it doesn't mention, as long as they're
individually conformant to the schema (and, on the FHIR side, pass validation - this
repo's own RIE converts inbound v2 to FHIR and validates that internally too, the same
check `03-laboratory-order-from-csv.ipynb`/`04-laboratory-report-fhir-from-hl7v2.ipynb`
run explicitly). So NE&Y Genomics is free to add fields of its own - exactly what the
5 NEY local-extension fields in the field-mapping table above already are - as long as
they stay conformant to both schemas.

This is the main advantage either HL7 standard has over exchanging flat files like
`Input/dWGS.csv` directly: producer and consumer aren't tightly coupled to one exact,
frozen column layout the way a raw CSV exchange would be. A new field can be added by
one side without breaking the other, which is what actually makes a CSV-based interface
brittle and costly to change compared to a schema built to expect extension.

(A worked example of the reverse direction - HL7 v2 into FHIR - is
`04-laboratory-report-fhir-from-hl7v2.ipynb`, which converts a `ORU^R01` laboratory
report the same hand-built way this notebook builds an order.)

## FHIR worked example

Same approach as `03-laboratory-order-from-csv.ipynb`: build the order by hand in
Python, validate resource-by-resource, then assemble and validate the whole `Bundle`.
Row 0 of `Input/dWGS.csv` (referral `r26000000201`, Rob Leeds, NHS number `9737383222` -
the same patient used throughout `03`-`05`) is the source data.

To keep this tractable, the worked example only builds the fields that already have a
confirmed (non-blank) `hl7v2_field`/`fhir_field` in the mapping table above. Every
`OPTIONAL` field still mapped as `""`/`""` (topography, morphology, QC metrics, rack
position, and so on) is a genuine open question for a future pass, not an oversight -
see the closing note.

In [3]:
import json
import os
import subprocess
import tempfile
from datetime import datetime
from uuid import uuid4

import requests
from dotenv import load_dotenv

load_dotenv()

toolsServer = os.getenv("V2_TOOLS")

NHS_NUMBER_SYSTEM = "https://fhir.nhs.uk/Id/nhs-number"
ODS_SYSTEM = "https://fhir.nhs.uk/Id/ods-organization-code"
V2_0203 = "http://terminology.hl7.org/CodeSystem/v2-0203"
SNOMED_SYSTEM = "http://snomed.info/sct"
GENOMIC_TEST_DIRECTORY_SYSTEM = "https://fhir.nhs.uk/CodeSystem/England-GenomicTestDirectory"
NW_GLH_ODS = "699X0"        # NW Genomics - the LAB-35 sub-order's Order Filler
GENOMICS_ENGLAND_ODS = "8J834"  # Genomics England - runs NGIS (National Genomic Informatics
                                 # System), the assigner of patient_ngis_id below

# glh_laboratory_id is Genomics England's short GLH code, not an ODS code - this maps it to
# the GLH's ODS code wherever FHIR/v2 needs one. "now" is from a real NW GLH manifest export;
# "yne" is assumed for NE&Y and not yet confirmed against a real NE&Y export.
GEL_GLH_ODS = {
    "yne": "699N0",  # YORKSHIRE AND NORTH EAST GLH
    "now": NW_GLH_ODS,
}

# primary_sample_state is a GEL enumeration, not SNOMED CT - mapped onto codes from NW-GMSA's
# specimen-type ValueSet (https://nw-gmsa.github.io/en/ValueSet-specimen-type.html).
PRIMARY_SAMPLE_STATE_SNOMED = {
    "blood_unsorted_edta": ("258580003", "Whole blood specimen (specimen)"),
    "boneMarrow_unsorted_edta": ("119359002", "Bone marrow specimen (specimen)"),
}

# NE&Y Genomics' three constituent labs' ODS codes, confirmed against the live NHS ODS API (see
# Background above). 699N0 is also the GLH's own registration, so it's what GEL_GLH_ODS["yne"] gives.
NEY_GLH_NAME = {
    "699N0": "Northern Genetics Service, Newcastle (NE&Y Genomics)",
    "699D0": "Sheffield Diagnostic Genetics Service (NE&Y Genomics)",
    "699C0": "The Leeds Genetics Laboratory (NE&Y Genomics)",
}

NWGMSA_PATIENT_PROFILE = "https://fhir.nwgenomics.nhs.uk/StructureDefinition/Patient"
NWGMSA_SERVICE_REQUEST_PROFILE = "https://fhir.nwgenomics.nhs.uk/StructureDefinition/ServiceRequest"
NWGMSA_SPECIMEN_PROFILE = "https://fhir.nwgenomics.nhs.uk/StructureDefinition/Specimen"
NWGMSA_FAMILY_GENETIC_GROUP_PROFILE = "https://fhir.nwgenomics.nhs.uk/StructureDefinition/FamilyGeneticGroup"
NWGMSA_PRACTITIONER_ROLE_PROFILE = "https://fhir.nwgenomics.nhs.uk/StructureDefinition/PractitionerRole"
NWGMSA_CODESYSTEM = "https://fhir.nwgenomics.nhs.uk/CodeSystem/NWGMSA"
NGIS_REFERRAL_ID_SYSTEM = "https://fhir.nwgenomics.nhs.uk/Identifier/NGIS-ReferralIdentifier"
# Identifier profiles (not declarable on the identifier itself - documented for traceability)
NGIS_REFERRAL_ID_PROFILE = "https://fhir.nwgenomics.nhs.uk/StructureDefinition/NGISReferralId"
ORDER_IDENTIFIER_PROFILE = "https://fhir.nwgenomics.nhs.uk/StructureDefinition/OrderIdentifier"
V3_ROLE_CODE = "http://terminology.hl7.org/CodeSystem/v3-RoleCode"


def details(item):
    return item["text"]


def issues_df(outcome):
    df = pd.DataFrame(outcome["issue"])
    df["details"] = df["details"].apply(details)
    df.drop(columns=["extension"], inplace=True, errors="ignore")
    df.sort_values(by=["severity"], inplace=True)
    df = df[~df["details"].str.contains("ValueSet/mimetypes")]
    df = df[~df["details"].str.contains("failed: dom-6")]
    df = df[~df["details"].str.contains("bcp:13")]
    df = df[~df["details"].str.contains("terminology service")]
    return df


def validate_resource(resource, profile):
    with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as tmp:
        json.dump(resource, tmp)
        tmp_path = tmp.name
    outcome_path = tmp_path + "-OperationOutcome.json"
    subprocess.run(
        [
            "java", "-jar", "validator_cli.jar", tmp_path,
            "-version", "4.0.1", "-ig", "package.tgz",
            "-profile", profile, "-tx", "n/a",
            "-output", outcome_path, "-output-style", "json",
        ],
        capture_output=True,
    )
    with open(outcome_path) as f:
        return issues_df(json.load(f))


row = dwgs_df.iloc[0]
glh_ods = GEL_GLH_ODS[row["glh_laboratory_id"]]
row[["referral_id", "clinical_indication_test_type_id", "patient_nhs_number", "patient_ngis_id",
     "ordering_entity_id", "glh_laboratory_id", "primary_sample_id_as_received_by_glh",
     "dispatched_sample_lsid", "glh_sample_consignment_number"]]

referral_id                                   r26000000201
clinical_indication_test_type_id                     R14.1
patient_nhs_number                              9737383222
patient_ngis_id                               p26000000101
ordering_entity_id                                     RR8
glh_laboratory_id                                      yne
primary_sample_id_as_received_by_glh              S26-1A01
dispatched_sample_lsid                          4000000001
glh_sample_consignment_number           NEY GLH 2026-08-26
Name: 0, dtype: str

### Filling the gaps: PDS demographics and local-extension stand-ins

As described under [Sample manifest data](#Sample-manifest-data), the patient's name isn't
in the national manifest. It's looked up from NHS England PDS (here, the repo's PDS
extracts) by `patient_nhs_number`, and the date of birth is checked against the
manifest's own `patient_date_of_birth` so a wrong match can't slip through. The
remaining non-demographic local-extension values come from `LOCAL_EXTENSION_STANDIN`,
keyed by `patient_ngis_id`. These are **stand-ins** until their real source is agreed,
not manifest data.

In [4]:
# NHS England PDS integration-environment extracts - stand-in for a live PDS (FHIR API) lookup.
pds_df = pd.concat(
    pd.read_csv(f"Input/PDS/{name}", dtype=str, keep_default_na=False, encoding="utf-8-sig")
    for name in ("NEY.csv", "NW.csv")
).set_index("NHS Number")

pds = pds_df.loc[row["patient_nhs_number"]]
assert pd.to_datetime(pds["Date Of Birth"], dayfirst=True).strftime("%Y-%m-%d") == row["patient_date_of_birth"], \
    "PDS date of birth doesn't match the manifest - wrong patient?"
patient_forename = pds["Forename"]
patient_surname = pds["Surname"]

# NW GMS local-extension values with no agreed source yet - NOT from the national manifest.
# Values are the ones Input/dWGS.csv carried before its local-extension columns were removed.
LOCAL_EXTENSION_STANDIN = {
    "p26000000101": {"family_structure": "Singleton", "participant_type": "Proband",
                    "clinical_information": "Suspected inherited neurodevelopmental condition."},
    "p26000000102": {"family_structure": "Duo", "participant_type": "Proband", "clinical_information": ""},
    "p26000000103": {"family_structure": "Duo", "participant_type": "Family Member", "clinical_information": ""},
    "p26000000104": {"family_structure": "Trio", "participant_type": "Proband",
                    "clinical_information": "Patient has intellectual disability"},
    "p26000000105": {"family_structure": "Trio", "participant_type": "Family Member", "clinical_information": ""},
    "p26000000106": {"family_structure": "Trio", "participant_type": "Family Member", "clinical_information": ""},
    # Rows added from the shape of a real GLH manifest export - no clinical_information invented.
    "p26000000107": {"family_structure": "Singleton", "participant_type": "Proband", "clinical_information": ""},
    "p26000000108": {"family_structure": "Singleton", "participant_type": "Proband", "clinical_information": ""},
    "p26000000109": {"family_structure": "Singleton", "participant_type": "Proband", "clinical_information": ""},
}
local_extension = LOCAL_EXTENSION_STANDIN[row["patient_ngis_id"]]

print(f"PDS: {patient_forename} {patient_surname} (DOB matches manifest)")
local_extension

PDS: Rob LEEDS (DOB matches manifest)

{'family_structure': 'Singleton',
 'participant_type': 'Proband',
 'clinical_information': 'Suspected inherited neurodevelopmental condition.'}

### Patient

`name` comes from the PDS lookup above, not from `Input/dWGS.csv`. No MR (hospital number)
identifier is built: `patient_medical_record_number` has no source yet, and PDS can't
supply one.

`patient_ngis_id` has no confirmed FHIR identifier *system* URI, but it does have a
confirmed **assigner**: NGIS (the National Genomic Informatics System) is a service run
by Genomics England, whose ODS code is `8J834` (confirmed against the live
[NHS ODS API](https://directory.spineservices.nhs.uk/ORD/2-0-0/organisations/8J834)) -
so rather than guess at a `system` URI, the identifier below carries `assigner` instead,
the same ODS-organisation-code pattern `Specimen.identifier.assigner` uses further down.
This resolves the field-mapping table's earlier `(TBC system)` flag for this field.
`type`, meanwhile, has an honest answer even without a confirmed `system`: v2-0203's
generic `PI` ("Patient internal identifier") fits exactly what this is - some other
system's internal ID for this patient - so it's coded rather than left text-only.

In [5]:
patient_fullurl = f"urn:uuid:{uuid4()}"
patient = {
    "resourceType": "Patient",
    "identifier": [
        {"system": NHS_NUMBER_SYSTEM, "type": {"coding": [{"system": V2_0203, "code": "NH"}]}, "value": row["patient_nhs_number"]},
        {"assigner": {"identifier": {"system": ODS_SYSTEM, "value": GENOMICS_ENGLAND_ODS}},
         "type": {"coding": [{"system": V2_0203, "code": "PI"}]}, "value": row["patient_ngis_id"]},
    ],
    "name": [{"family": patient_surname, "given": [patient_forename]}],  # from PDS - not in the national manifest
    "birthDate": row["patient_date_of_birth"],
}
print(json.dumps(patient, indent=2))

{
  "resourceType": "Patient",
  "identifier": [
    {
      "system": "https://fhir.nhs.uk/Id/nhs-number",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "NH"
          }
        ]
      },
      "value": "9737383222"
    },
    {
      "assigner": {
        "identifier": {
          "system": "https://fhir.nhs.uk/Id/ods-organization-code",
          "value": "8J834"
        }
      },
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "PI"
          }
        ]
      },
      "value": "p26000000101"
    }
  ],
  "name": [
    {
      "family": "LEEDS",
      "given": [
        "Rob"
      ]
    }
  ],
  "birthDate": "1978-01-17"
}

In [6]:
validate_resource(patient, NWGMSA_PATIENT_PROFILE)

Empty DataFrame
Columns: [severity, code, details, expression]
Index: []

### FamilyGeneticGroup: family structure and participant type

`family_structure` and `participant_type` (local-extension fields - from the stand-in
above, not the national manifest) describe the family this patient is being
tested with, so they go in a
[`FamilyGeneticGroup`](https://nw-gmsa.github.io/en/StructureDefinition-FamilyGeneticGroup.html)
`Group` rather than in `Observation`s:

- **`identifier`** - `referral_id`, using the IG's `ReferralId` slice (NGIS Referral Id,
  system `NGIS-ReferralIdentifier`). It is assigned by Genomics England (`8J834`, the
  same NGIS assigner as `patient_ngis_id` above), and `type` is v2-0203 `PGN` (Placer
  Group Number), matching the IG's own
  [dWGS Trio example](https://nw-gmsa.github.io/en/Group-FamilyGeneticGroup-dWGS-Trio-r26000000203.html).
  This exact identifier is reused as `ServiceRequest.requisition` below, and the
  `ServiceRequest` also references this `Group` from `supportingInfo`.
- **`code`** - `family_structure`, coded from the
  [FamilyStructure](https://nw-gmsa.github.io/en/ValueSet-FamilyStructure.html) value set
  (`FamilyStructureSingleton`/`Duo`/`Trio`). `quantity` is the number of members.
- **`member`** - **the whole family**: one member per `Input/dWGS.csv` row that shares
  this order's `referral_id`, in CSV order. The cell checks that the member count matches
  `family_structure` (1/2/3) and that the family has exactly one proband. Every family
  member's order carries an identical `Group` (only the reference to its own patient
  differs), so whoever receives the messages doesn't have to rebuild the family from
  separate orders. This message's own patient is referenced by `fullUrl` (and NHS
  number). The other members' `Patient` resources travel in their own messages, so here
  they're logical references: NHS number as `identifier`, with `patient_ngis_id` as
  `display`, the same shape as the IG's dWGS Trio example. Each member's
  `FamilyMemberRelationship` extension comes from that row's `participant_type`: `Proband`
  becomes `ONESELF`, and `Family Member` becomes the generic `FAMMEMB` (as in the IG's
  dWGS example). Neither field says how a family member is related to the proband
  (mother, father, sibling...), so nothing more specific can be coded. That's also why
  the family is a `Group` and not a set of `RelatedPerson`s. The manifest tells us these
  patients are linked for genetic testing, but not how they're related, and a
  `RelatedPerson` needs that relationship.

In [7]:
FAMILY_STRUCTURE_CODES = {
    "Singleton": ("FamilyStructureSingleton", 1),
    "Duo": ("FamilyStructureDuo", 2),
    "Trio": ("FamilyStructureTrio", 3),
}
PARTICIPANT_TYPE_RELATIONSHIP = {
    "Proband": ("ONESELF", "self"),
    "Family Member": ("FAMMEMB", "family member"),
}

# NGISReferralId - shared with ServiceRequest.requisition below.
referral_identifier = {
    "type": {"coding": [{"system": V2_0203, "code": "PGN"}]},
    "system": NGIS_REFERRAL_ID_SYSTEM,
    "value": row["referral_id"],
    "assigner": {"identifier": {"system": ODS_SYSTEM, "value": GENOMICS_ENGLAND_ODS}},
}

family_structure_code, family_size = FAMILY_STRUCTURE_CODES[local_extension["family_structure"]]
relationship_code, relationship_display = PARTICIPANT_TYPE_RELATIONSHIP[local_extension["participant_type"]]

# The whole family: every participant sharing this order's referral_id. A cancer referral has
# two rows (germline + tumour sample) for its one participant, so dedupe by patient_ngis_id.
family_rows = dwgs_df[dwgs_df.referral_id == row["referral_id"]].drop_duplicates("patient_ngis_id")
family_participants = [LOCAL_EXTENSION_STANDIN[ngis_id] for ngis_id in family_rows.patient_ngis_id]
assert {p["family_structure"] for p in family_participants} == {local_extension["family_structure"]}, \
    "family_structure must be the same on every row of a referral"
assert len(family_rows) == family_size, \
    f"{local_extension['family_structure']} referral {row['referral_id']} has {len(family_rows)} participant(s)"
assert [p["participant_type"] for p in family_participants].count("Proband") == 1, "exactly one Proband per referral"


def family_member(member_row, participant):
    code, display = PARTICIPANT_TYPE_RELATIONSHIP[participant["participant_type"]]
    nhs_number = {"system": NHS_NUMBER_SYSTEM, "value": member_row["patient_nhs_number"]}
    if member_row["patient_ngis_id"] == row["patient_ngis_id"]:
        entity = {"reference": patient_fullurl, "type": "Patient", "identifier": nhs_number}  # this message's patient
    else:
        entity = {"type": "Patient", "identifier": nhs_number, "display": member_row["patient_ngis_id"]}  # in its own message
    return {
        "extension": [{
            "url": "https://fhir.nwgenomics.nhs.uk/StructureDefinition/FamilyMemberRelationship",
            "valueCodeableConcept": {"coding": [{"system": V3_ROLE_CODE, "code": code, "display": display}]},
        }],
        "entity": entity,
    }


family_group_fullurl = f"urn:uuid:{uuid4()}"
family_group = {
    "resourceType": "Group",
    "meta": {"profile": [NWGMSA_FAMILY_GENETIC_GROUP_PROFILE]},
    "identifier": [referral_identifier],
    "type": "person",
    "actual": True,
    "code": {"coding": [{"system": NWGMSA_CODESYSTEM, "code": family_structure_code, "display": local_extension["family_structure"]}]},
    "quantity": len(family_rows),
    "member": [family_member(r, p) for (_, r), p in zip(family_rows.iterrows(), family_participants)],
}

print(json.dumps(family_group, indent=2))

{
  "resourceType": "Group",
  "meta": {
    "profile": [
      "https://fhir.nwgenomics.nhs.uk/StructureDefinition/FamilyGeneticGroup"
    ]
  },
  "identifier": [
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "PGN"
          }
        ]
      },
      "system": "https://fhir.nwgenomics.nhs.uk/Identifier/NGIS-ReferralIdentifier",
      "value": "r26000000201",
      "assigner": {
        "identifier": {
          "system": "https://fhir.nhs.uk/Id/ods-organization-code",
          "value": "8J834"
        }
      }
    }
  ],
  "type": "person",
  "actual": true,
  "code": {
    "coding": [
      {
        "system": "https://fhir.nwgenomics.nhs.uk/CodeSystem/NWGMSA",
        "code": "FamilyStructureSingleton",
        "display": "Singleton"
      }
    ]
  },
  "quantity": 1,
  "member": [
    {
      "extension": [
        {
          "url": "https://fhir.nwgenomics.nhs.uk/StructureDefinition/FamilyMemberRelationship",
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/v3-RoleCode",
                "code": "ONESELF",
                "display": "self"
              }
            ]
          }
        }
      ],
      "entity": {
        "reference": "urn:uuid:3adce7f2-72c9-4791-8248-188b7abfd6a5",
        "type": "Patient",
        "identifier": {
          "system": "https://fhir.nhs.uk/Id/nhs-number",
          "value": "9737383222"
        }
      }
    }
  ]
}

In [8]:
validate_resource(family_group, NWGMSA_FAMILY_GENETIC_GROUP_PROFILE)

,severity,code,details,expression
0,warning,code-invalid,None of the codings provided are in the value ...,[Group.identifier[0].type]

The one `error` is `PGN` (Placer Group Number) on `identifier.type`, and it's a
terminology-version problem, not a modelling one. With `-tx n/a` the validator checks
`v2-0203` against its own offline copy (version 2.9), which is older than `PGN`. The
IG's own
[dWGS Trio example](https://nw-gmsa.github.io/en/Group-FamilyGeneticGroup-dWGS-Trio-r26000000203.html)
uses the same code, so it would fail the same way. Because the `ServiceRequest` below
reuses this identifier as its `requisition`, the same error shows up there in the
`Bundle` validation. It also has a knock-on effect there: because the `Group` fails on
that one code, the validator doesn't count it as a `FamilyGeneticGroup`. It then reports
`ServiceRequest.supportingInfo` as matching none of its slices ("Unable to find a
profile match"). Validating a copy with `PGN` removed made that error disappear, and the
reference matched the `familyGeneticGroup` slice cleanly. So it's the same terminology
issue, not a problem with the reference. The `Specimen` reference error has the same
kind of cause: its own `container` errors. Everything else about the `Group` (the `ReferralId` slice, the
`FamilyStructure` code, the `FamilyMemberRelationship` extension) passes the profile.

### Specimen

One `Specimen`, not two: `dWGS.csv`'s primary-specimen and dispatched-specimen fields
both describe the same physical sample as it moves through this sub-order, so they're
carried as multiple identifiers on a single resource rather than two linked resources.
Two of those identifiers have different **assigners**, reflecting who actually issued
each one:

- **Received Sample Identifier** (`primary_sample_id_as_received_by_glh`) - assigned by
  `ordering_entity_id` (Leeds, `RR8`), the *original* order placer who received and
  labelled the specimen before it was sent on. Coded `type` `PLAC` ("Placer
  Identifier") - the identifier assigned by whoever placed the order/collected the
  specimen.
- **LIMS Sample Identifier** (`primary_sample_id_in_glh_lims`) - assigned by
  `glh_laboratory_id` (`yne`, so ODS `699N0`), NE&Y Genomics' own LIMS, once the specimen was logged
  there. Coded `type` `FILL` ("Filler Identifier") - the identifier assigned by the
  party filling/processing the order.

`glh_sample_consignment_number` becomes the `identifier:ShipmentTrackingNumber` slice,
coded `type` `STN` ("Shipment Tracking Number"), per the field-mapping table above.
Those three `type` codes are from
[HL7's v2-0203 CodeSystem](http://terminology.hl7.org/CodeSystem/v2-0203) - the same
system already used for `Patient.identifier.type` above - rather than left text-only.

`dispatched_sample_lsid` (Specimen Barcode) becomes `Specimen.container.identifier`,
coded `type` `ZCID` per the field-mapping table's `SPM-2.1 (type=ZCID)` mapping - unlike
the other three, `ZCID` is a NE&Y Genomics locally-defined ("Z") identifier-type code,
not one of HL7's own v2-0203 values, but it's carried in the same `type.coding` shape
since that's the field it actually populates in the v2 message.

`primary_sample_state` no longer stays text-only either. `Input/dWGS.csv` carries GEL's
own enumeration (e.g. `blood_unsorted_edta`), the same as a real GLH manifest export, and
`PRIMARY_SAMPLE_STATE_SNOMED` maps it onto a code from NW-GMSA's own [specimen-type
ValueSet](https://nw-gmsa.github.io/en/ValueSet-specimen-type.html) (e.g. `258580003`
Whole blood specimen) to give a proper `Specimen.type` `Coding`. `primary_sample_type` (the germline/tumour classifier)
and `dispatched_sample_state` remain text-only/unused, though - `primary_sample_type`
is still flagged low-confidence in the field-mapping table above, and nothing in this
worked example builds `dispatched_sample_state` into any resource yet (see the
discrepancy check below).

Three more fields land on `Specimen.collection`/`Specimen.bodySite`:
`dna_extraction_protocol` becomes `collection.method` when present - text-only, since its
values (e.g. `"Qiagen"`) name a vendor/kit, not a coded procedure with a confirmed SNOMED
CT equivalent. It's blank in `Input/dWGS.csv`, as in the real export: the data mapping
workbook says covaris/qiagen only apply to FFPE samples, and these are germline blood. Worth flagging: `collection.method` is normally *how the specimen was
collected* (e.g. venipuncture), not how the dispatched DNA specimen was later
extracted from it - a same kind of imperfect-fit call the field-mapping table already
makes elsewhere, not something to paper over. `dispatched_sample_volume_(ul)` becomes
`collection.quantity`, a proper UCUM `Quantity` (`uL`) rather than free text.
`received_sample_topography` would become `bodySite` - `MUST (cancer only)`, and
`Input/dWGS.csv`'s rare-disease rows correctly leave it blank, so it's built only when
present rather than added as an empty `CodeableConcept`.

In [9]:
specimen_fullurl = f"urn:uuid:{uuid4()}"
primary_sample_type_code, primary_sample_type_display = PRIMARY_SAMPLE_STATE_SNOMED[row["primary_sample_state"]]
specimen = {
    "resourceType": "Specimen",
    "identifier": [
        {"type": {"coding": [{"system": V2_0203, "code": "PLAC"}]}, "value": row["primary_sample_id_as_received_by_glh"]},
        {"assigner": {"identifier": {"system": ODS_SYSTEM, "value": glh_ods}},
         "type": {"coding": [{"system": V2_0203, "code": "FILL"}]}, "value": row["primary_sample_id_in_glh_lims"]},
        {"assigner": {"identifier": {"system": ODS_SYSTEM, "value": glh_ods}},
         "type": {"coding": [{"system": V2_0203, "code": "STN"}]}, "value": row["glh_sample_consignment_number"]},
    ],
    "type": {"coding": [{"system": SNOMED_SYSTEM,
                          "code": primary_sample_type_code,
                          "display": primary_sample_type_display}]},
    "subject": {"reference": patient_fullurl},
    "collection": {
        "quantity": {"value": float(row["dispatched_sample_volume_(ul)"]), "unit": "uL",
                     "system": "http://unitsofmeasure.org", "code": "uL"},
    },
    "receivedTime": row["primary_sample_received_date"] + "T00:00:00+00:00",
    "container": [{"identifier": [
        {"type": {"coding": [{"system": V2_0203, "code": "ZCID"}]}, "value": row["dispatched_sample_lsid"]}
    ]}],
}
# ordering_entity_id and received_sample_collection_date are optional, and a real GLH manifest
# export leaves both blank - leave the assigner/collectedDateTime out rather than guess them.
if row["ordering_entity_id"]:
    specimen["identifier"][0]["assigner"] = {"identifier": {"system": ODS_SYSTEM, "value": row["ordering_entity_id"]}}
if row["received_sample_collection_date"]:
    specimen["collection"]["collectedDateTime"] = row["received_sample_collection_date"] + "T00:00:00+00:00"
# dna_extraction_protocol is blank for germline blood (covaris/qiagen only apply to FFPE).
if row["dna_extraction_protocol"]:
    specimen["collection"]["method"] = {"text": row["dna_extraction_protocol"]}
if row["received_sample_topography"]:
    specimen["bodySite"] = {"text": row["received_sample_topography"]}

print(json.dumps(specimen, indent=2))

{
  "resourceType": "Specimen",
  "identifier": [
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "PLAC"
          }
        ]
      },
      "value": "S26-1A01",
      "assigner": {
        "identifier": {
          "system": "https://fhir.nhs.uk/Id/ods-organization-code",
          "value": "RR8"
        }
      }
    },
    {
      "assigner": {
        "identifier": {
          "system": "https://fhir.nhs.uk/Id/ods-organization-code",
          "value": "699N0"
        }
      },
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "FILL"
          }
        ]
      },
      "value": "S26-1A01"
    },
    {
      "assigner": {
        "identifier": {
          "system": "https://fhir.nhs.uk/Id/ods-organization-code",
          "value": "699N0"
        }
      },
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "STN"
          }
        ]
      },
      "value": "NEY GLH 2026-08-26"
    }
  ],
  "type": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "258580003",
        "display": "Whole blood specimen (specimen)"
      }
    ]
  },
  "subject": {
    "reference": "urn:uuid:3adce7f2-72c9-4791-8248-188b7abfd6a5"
  },
  "collection": {
    "quantity": {
      "value": 150.0,
      "unit": "uL",
      "system": "http://unitsofmeasure.org",
      "code": "uL"
    },
    "collectedDateTime": "2026-08-18T00:00:00+00:00"
  },
  "receivedTime": "2026-08-20T00:00:00+00:00",
  "container": [
    {
      "identifier": [
        {
          "type": {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                "code": "ZCID"
              }
            ]
          },
          "value": "4000000001"
        }
      ]
    }
  ]
}

In [10]:
validate_resource(specimen, NWGMSA_SPECIMEN_PROFILE)

,severity,code,details,expression
3,error,structure,Specimen.container.extension: minimum required...,[Specimen.container[0]]
4,error,structure,Slice 'Specimen.container.extension:device' fo...,[Specimen.container[0]]
5,error,code-invalid,Unknown code 'ZCID' in the CodeSystem 'http://...,[Specimen.container[0].identifier[0].type.codi...
0,warning,code-invalid,None of the codings provided are in the value ...,[Specimen.identifier[2].type]
6,warning,code-invalid,None of the codings provided are in the value ...,[Specimen.container[0].identifier[0].type]

**IG 2.2.1 update:** re-validating against the current NW-GMSA package (2.2.1; this
section was written against 2.0.3) adds two new `structure` errors.
`Specimen.container.extension:device` is now required (min 1), and nothing here
populates it yet. This comes from the IG's `Specimen` profile changing, not from this
notebook, and it's still open. The `ZCID`/`STN` issues described below are unchanged.

That `Specimen.type` error is gone now that `primary_sample_state` supplies a real
SNOMED CT code - the `warning` on `identifier[2].type` is unchanged from before: `STN`
isn't itself bound to the value set NW-GMSA's `Specimen` profile expects for that slice,
though it's still the correct v2-0203 code for what it represents (see the Specimen
section above). Coding `container[0].identifier[0].type` as `ZCID` adds two new issues
instead of resolving cleanly: an `error` because `ZCID` isn't a real v2-0203 code (it's
NE&Y Genomics' own local extension, as flagged above) so the validator can't resolve it
against that CodeSystem at all, plus the same kind of value-set `warning` `STN` gets.
None of this stops the HL7 v2 transform below from running, and - unlike before the
`primary_sample_state` fix - that field now survives into the v2 output as a properly
coded `SPM-4` rather than silently disappearing (see the discrepancy check below).
`dispatched_sample_state` remains a separate, still-open gap: nothing in this worked
example builds it into any resource at all yet, coded or not.

### PractitionerRole: who approved the sub-order

`approved_by` is the GLH lead who approved the case for WGS (SOP Appendix 3, column 37).
When it's present, `ServiceRequest.requester` references a
[`PractitionerRole`](https://nw-gmsa.github.io/en/StructureDefinition-PractitionerRole.html)
rather than just the requesting GLH organisation:

- **`organization`** - the requesting GLH: `glh_laboratory_id`'s ODS code, via `GEL_GLH_ODS` (the
  profile requires `organization.identifier`), plus the lab's name.
- **`practitioner`** - `display` only, set to the `approved_by` text. The manifest gives
  a name but no identifier (no GMC/HCPC number), and the IG's `Practitioner` profile
  requires a `PractitionerIdentifier`, so a separate `Practitioner` resource can't be
  built. The IG's own `PractitionerRole` examples use the same display-only shape
  (e.g. "Result INTERPRETER" at North West Genomics `699X0`).

When `approved_by` is blank, `requester` stays a logical reference to the GLH
`Organization` (ODS code). The national manifest leaves `approved_by` optional, and NW
GMS doesn't require it. Every row in `Input/dWGS.csv` today has
`"Duty Scientist on behalf of NEY GMS"`, which describes a role rather than naming a
person, but that is what the manifest carries. The transformation spec doesn't map
`approved_by` to HL7 v2, so whether `/transformToV2` carries it (e.g. into `ORC-12`
Ordering Provider) still needs the transform re-run.

In [11]:
glh_organisation = {
    "identifier": {"system": ODS_SYSTEM, "value": glh_ods},
    "display": NEY_GLH_NAME[glh_ods],
}

practitioner_role = None
if row["approved_by"].strip():
    practitioner_role_fullurl = f"urn:uuid:{uuid4()}"
    practitioner_role = {
        "resourceType": "PractitionerRole",
        "meta": {"profile": [NWGMSA_PRACTITIONER_ROLE_PROFILE]},
        "practitioner": {"display": row["approved_by"]},  # name only - no identifier in the manifest
        "organization": glh_organisation,
    }
    requester = {"reference": practitioner_role_fullurl, "type": "PractitionerRole"}
    print(json.dumps(practitioner_role, indent=2))
else:
    requester = {**glh_organisation, "type": "Organization"}  # no approved_by - the GLH itself
    print("approved_by blank - requester is the GLH Organization:", json.dumps(requester))

{
  "resourceType": "PractitionerRole",
  "meta": {
    "profile": [
      "https://fhir.nwgenomics.nhs.uk/StructureDefinition/PractitionerRole"
    ]
  },
  "practitioner": {
    "display": "Duty Scientist on behalf of NEYGLH Medical"
  },
  "organization": {
    "identifier": {
      "system": "https://fhir.nhs.uk/Id/ods-organization-code",
      "value": "699N0"
    },
    "display": "Northern Genetics Service, Newcastle (NE&Y Genomics)"
  }
}

In [12]:
validate_resource(practitioner_role, NWGMSA_PRACTITIONER_ROLE_PROFILE) if practitioner_role else None

Empty DataFrame
Columns: [severity, code, details, expression]
Index: []

### ServiceRequest

For this `LAB-35` sub-order, `requester` is `glh_laboratory_id` (NE&Y Genomics, ODS
`699N0` via `GEL_GLH_ODS`), via the `approved_by`
`PractitionerRole` above when there is one - the party actually placing *this*
order with NW Genomics - not `ordering_entity_id` (the *original* referring Trust).
`requisition` (Order Group Number, `ORC-4`) is `referral_id`, and it is the exact
`referral_identifier` the `FamilyGeneticGroup` above uses (NGIS Referral Id, assigned by
Genomics England `8J834`). Earlier passes treated it as NE&Y Genomics' own group number
assigned by `glh_laboratory_id`. The IG now identifies it as the NGIS `referral_id` from
TOMS. `supportingInfo` references the `FamilyGeneticGroup` itself (the profile's
`familyGeneticGroup` slice, 0..1), so the `Group` isn't left orphaned in the message.
`requisition` and `Group.identifier` still carry the same `referral_id`, so each
family member's separate order can be matched to the others by that value too. The referring Trust's role is preserved instead as the `Specimen`
identifier assigner above - the original order placer's involvement doesn't disappear,
it just isn't `ServiceRequest.requester` for *this* message.

`intent` is `filler-order`, not the plain `order` `03-laboratory-order-from-csv.ipynb`
used - this `ServiceRequest` is NW Genomics (the filler) restating NE&Y Genomics'
sub-order, not an original order in its own right.

`intent` isn't always `filler-order`, though: when `retrospective_sample` is
`"Retrospective"` rather than `"New"`, NW Genomics is reflexing further testing off a
specimen it already has - not NE&Y Genomics placing a fresh sub-order - so `intent`
switches to `reflex-order`. Every row in `Input/dWGS.csv` today is `"New"`, so this
worked example's output doesn't change, but the field-mapping table above now records
the distinction.

Two identifiers, each following its own NW-GMSA identifier profile:

- **`requisition`** (Order Group Number, `ORC-4`) -
  [NGIS Referral Id](https://nw-gmsa.github.io/en/StructureDefinition-NGISReferralId.html):
  `referral_id`, system `https://fhir.nwgenomics.nhs.uk/Identifier/NGIS-ReferralIdentifier`,
  `type` `PGN` (from its base `OrderGroupNumber` profile), assigned by Genomics England
  `8J834`. It's shared by every participant in a family, so on its own it does **not**
  identify one order.
- **`identifier`** (Order Placer Number) - the `OrderIdentifier` slice:
  `dispatched_sample_lsid` (e.g. `4000000001`), `type` `PLAC`, assigned by the sending
  lab's ODS code (`glh_ods`, `699N0` here). This is the proposed `placer_order_number`
  (the NW-GMSA use cases `dWGS.md`, "placer_order_number: use the LSID"). It replaces the
  earlier NGIS Composite Order Number (`f"{referral_id}-{patient_ngis_id}"`, `FILL`,
  `8J834`), which couldn't be the placer order number because it isn't unique. A real GLH
  manifest export lists a cancer referral's germline and tumour samples as two rows for the
  same patient, so both rows have the same `referral_id` and `patient_ngis_id`. The LSID is
  the barcode of one dispatched tube, so it's unique per manifest row. Each row, including
  each half of a tumour-normal pair, is therefore its own order with its own `Specimen`. The
  cell below asserts that across every manifest row, not just this one. The same LSID also
  stays on `Specimen.container.identifier` (`ZCID`). The profile defines no `system`, so none
  is set.

In [13]:
service_request_fullurl = f"urn:uuid:{uuid4()}"
# retrospective_sample == "Retrospective" means this sub-order is NW Genomics reflexing
# testing off an already-received specimen, not NE&Y Genomics placing a fresh filler
# order - every row in Input/dWGS.csv today is "New", so this stays "filler-order" in
# practice, but the switch is real.
service_request_intent = "reflex-order" if row["retrospective_sample"] == "Retrospective" else "filler-order"


# Order Placer Number = dispatched_sample_lsid (proposed placer_order_number). It must be unique per
# manifest row - referral_id/patient_ngis_id aren't (Duo/Trio families, and a cancer referral's
# germline + tumour rows for the same patient, share them).
assert dwgs_df.dispatched_sample_lsid.is_unique, \
    dwgs_df[dwgs_df.dispatched_sample_lsid.duplicated(keep=False)].dispatched_sample_lsid.tolist()

order_identifier = {  # ORDER_IDENTIFIER_PROFILE (ServiceRequest.identifier:OrderIdentifier)
    "type": {"coding": [{"system": V2_0203, "code": "PLAC"}]},
    "value": row["dispatched_sample_lsid"],
    "assigner": {"identifier": {"system": ODS_SYSTEM, "value": glh_ods}},  # the sending lab
}

service_request = {
    "resourceType": "ServiceRequest",
    "status": "active",
    "intent": service_request_intent,
    "category": [{"coding": [{"system": "http://snomed.info/sct", "code": "116148004"}]}],
    "code": {"coding": [{"system": GENOMIC_TEST_DIRECTORY_SYSTEM, "code": row["clinical_indication_test_type_id"]}]},
    "requisition": referral_identifier,  # NGIS_REFERRAL_ID_PROFILE - same value as family_group.identifier
    "identifier": [order_identifier],
    "subject": {"reference": patient_fullurl},
    "requester": requester,  # PractitionerRole (approved_by) or the GLH Organization - see above
    "specimen": [{"reference": specimen_fullurl, "type": "Specimen"}],
    "supportingInfo": [{"reference": family_group_fullurl, "type": "Group"}],  # familyGeneticGroup slice
}

# clinical_information is optional - leave note out rather than emit an empty string.
if local_extension["clinical_information"]:
    service_request["note"] = [{"text": local_extension["clinical_information"]}]  # local-extension stand-in

print(json.dumps(service_request, indent=2))

{
  "resourceType": "ServiceRequest",
  "status": "active",
  "intent": "filler-order",
  "category": [
    {
      "coding": [
        {
          "system": "http://snomed.info/sct",
          "code": "116148004"
        }
      ]
    }
  ],
  "code": {
    "coding": [
      {
        "system": "https://fhir.nhs.uk/CodeSystem/England-GenomicTestDirectory",
        "code": "R14.1"
      }
    ]
  },
  "requisition": {
    "type": {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
          "code": "PGN"
        }
      ]
    },
    "system": "https://fhir.nwgenomics.nhs.uk/Identifier/NGIS-ReferralIdentifier",
    "value": "r26000000201",
    "assigner": {
      "identifier": {
        "system": "https://fhir.nhs.uk/Id/ods-organization-code",
        "value": "8J834"
      }
    }
  },
  "identifier": [
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "PLAC"
          }
        ]
      },
      "value": "4000000001",
      "assigner": {
        "identifier": {
          "system": "https://fhir.nhs.uk/Id/ods-organization-code",
          "value": "699N0"
        }
      }
    }
  ],
  "subject": {
    "reference": "urn:uuid:3adce7f2-72c9-4791-8248-188b7abfd6a5"
  },
  "requester": {
    "reference": "urn:uuid:4d5fb3ec-20c7-4ede-af0d-38be9be840a2",
    "type": "PractitionerRole"
  },
  "specimen": [
    {
      "reference": "urn:uuid:d653019e-5e3f-42ee-9a51-899309c2b73c",
      "type": "Specimen"
    }
  ],
  "supportingInfo": [
    {
      "reference": "urn:uuid:410dfab0-89bc-4e2c-8225-71a6dab40545",
      "type": "Group"
    }
  ],
  "note": [
    {
      "text": "Suspected inherited neurodevelopmental condition."
    }
  ]
}

In [14]:
validate_resource(service_request, NWGMSA_SERVICE_REQUEST_PROFILE)

,severity,code,details,expression
0,information,informational,This element does not match any known slice de...,[ServiceRequest.supportingInfo[0]]

**IG 2.2.1 update:** this now validates cleanly. The `authoredOn` cardinality error
described below no longer appears against the current package, so `ServiceRequest.authoredOn`
appears to have been relaxed in the profile. The paragraph is kept for history.
Pointing `supportingInfo` at the `FamilyGeneticGroup` instead of the two `Observation`s
introduced no new issues.

The remaining `error` (`ServiceRequest.authoredOn: minimum required = 1`) is the
same pre-existing NW-GMSA profile gap `04-laboratory-report-fhir-from-hl7v2.ipynb`
already found and confirmed against this repo's real production output: nothing in
`dWGS.csv` records when the order was authored, so - as there - it's left out rather
than filled with an invented date.

### MessageHeader and the Bundle

`sender` is NE&Y Genomics (`699N0`, looked up from `glh_laboratory_id` `yne`, this `LAB-35` sub-order's Order Placer);
`destination` is NW Genomics (`699X0`, the Order Filler). `Bundle.identifier`/
`.timestamp` are mandatory on the
[`Bundle` (message) profile](https://nw-gmsa.github.io/en/StructureDefinition-BundleMessage.html),
as throughout this series. The `FamilyGeneticGroup` goes in as its own entry,
referenced from `ServiceRequest.supportingInfo`, so it is reachable forwards from
`MessageHeader.focus` (the `ServiceRequest`) like every other entry. The
`PractitionerRole`, when there is one, is reachable the same way, via
`ServiceRequest.requester`.

In [15]:
message_header = {
    "resourceType": "MessageHeader",
    "eventCoding": {"system": "http://terminology.hl7.org/CodeSystem/v2-0003", "code": "O21"},
    "sender": {"identifier": {"system": ODS_SYSTEM, "value": glh_ods}},
    "destination": [{"endpoint": "https://fhir.nwgenomics.nhs.uk/Endpoint/RIE",
                      "receiver": {"identifier": {"system": ODS_SYSTEM, "value": NW_GLH_ODS}}}],
    "source": {"endpoint": "https://fhir.nwgenomics.nhs.uk/Endpoint/NEYGenomics", "software": "NE&Y Genomics"},
    "focus": [{"reference": service_request_fullurl}],
}

order_bundle = {
    "resourceType": "Bundle",
    "identifier": {"value": f"urn:uuid:{uuid4()}"},
    "timestamp": datetime.now().astimezone().strftime("%Y-%m-%dT%H:%M:%S+00:00"),
    "type": "message",
    "entry": [
        {"fullUrl": f"urn:uuid:{uuid4()}", "resource": message_header},
        {"fullUrl": patient_fullurl, "resource": patient},
        {"fullUrl": specimen_fullurl, "resource": specimen},
        {"fullUrl": family_group_fullurl, "resource": family_group},
        {"fullUrl": service_request_fullurl, "resource": service_request},
    ],
}

if practitioner_role:
    order_bundle["entry"].insert(-1, {"fullUrl": practitioner_role_fullurl, "resource": practitioner_role})

order_filename = f"dWGS_{row['referral_id']}.json"
with open("Input/FHIR/O21/" + order_filename, "w") as f:
    json.dump(order_bundle, f, indent=2)

print("Saved Input/FHIR/O21/" + order_filename)

Saved Input/FHIR/O21/dWGS_r26000000201.json

In [16]:
outcome_path = "Results/FHIR/O21/" + order_filename + "-OperationOutcome.json"
subprocess.run(
    [
        "java", "-jar", "validator_cli.jar", "Input/FHIR/O21/" + order_filename,
        "-version", "4.0.1", "-ig", "package.tgz",
        "-bundle", "ServiceRequest:0", NWGMSA_SERVICE_REQUEST_PROFILE, "-tx", "n/a",
        "-output", outcome_path, "-output-style", "json",
    ],
    capture_output=True,
)
with open(outcome_path) as f:
    issues_df(json.load(f))

## HL7 v2 worked example

Same `transformToV2` tooling endpoint used throughout this series. An earlier draft of
this `Bundle` - before the `Patient.identifier[1].type` fix above (`coding` + `text`
together, which turned out to violate a fixed value the profile pins that slice to) -
got a `500` back with an empty body from this same call. That's worth knowing even
though it's fixed now: a structural profile violation on `Patient` was enough to fail
the *whole* transform, not just that one field, with nothing in the response to say
why - the `FHIR Validation.ipynb`-style checks above are what actually located it.

### Expected `OML^O21` order numbers and assigners (hand-built)

Before calling the transform, this cell builds the `OML^O21` the FHIR above *should*
become, straight from the notebook's own resources, so the order numbers and their
assigners can be checked. It follows the IG's dWGS field mapping (`dWGS.md`) and the
transformation spec. **This is an expected message, not transform output.** The
transform's actual output comes from the call below.

| v2 field | Value | From |
|---|---|---|
| `PID-3` (NGIS) | `p…^^^8J834^PI` | `Patient.identifier` (PI, assigner Genomics England `8J834`) |
| `ORC-2` / `OBR-2` Placer Order Number | `<LSID>^<GLH ODS>` | `ServiceRequest.identifier:OrderIdentifier` - `dispatched_sample_lsid` (`PLAC`, assigner = sending lab ODS) |
| `ORC-3` / `OBR-3` Filler Order Number | *empty* | assigned by NW Genomics (the Order Filler) once it accepts the order |
| `ORC-4` Placer Group Number | `r…^8J834` | `ServiceRequest.requisition` - NGIS Referral Id (`PGN`, assigner `8J834`) |
| `ORC-21` Ordering Facility | `^^<GLH ODS>^^^ODS` | requesting GLH (`PractitionerRole.organization`) |
| `OBX` `NGIS_REFERRAL_ID` / `FAMILY_STRUCTURE` / `PARTICIPANT_TYPE` / `DISPATCHED_SAMPLE_LSID` | values | `referral_id`, `Group.code`, member relationship, `Specimen.container.identifier` |

Two points to note. The first is that **`ORC-2`/`OBR-2` now carry the LSID**. The
transformation spec v0.2 makes them mandatory and requires them to be identical. Both
hold `placer_order_number`, taken from `dispatched_sample_lsid` with the sending lab's
ODS code as its assigning authority. `SPM-2.1` (`ZCID`) still carries the LSID as the
container identifier, so the same value appears in both places. `ORC-3`/`OBR-3` (Filler
Order Number) are left for NW Genomics to assign; the earlier NGIS Composite Order Number
(`r…-p…^8J834`) that sat there isn't unique per order, so it's no longer built.
The second is that the transformation spec's worked example writes the NGIS patient
identifier as `^^^NGIS^NGIS`, while the IG's `dWGS.md` uses `^^^8J834^PI` (assigning
authority = Genomics England's ODS code, consistent with every other assigner here).
This follows the IG.

In [17]:
def ei(identifier):
    """HL7 v2 EI (Entity Identifier^Namespace ID) from a FHIR Identifier - namespace = assigner ODS code."""
    return f"{identifier['value']}^{identifier['assigner']['identifier']['value']}"


def v2_date(value):
    return value.replace("-", "")


def v2_datetime(value):
    return value[:10].replace("-", "") + "000000+0000"


ngis_identifier = next(i for i in patient["identifier"] if i.get("assigner"))
placer_order_number = ei(service_request["identifier"][0])   # LSID, assigned by the sending lab
placer_group_number = ei(service_request["requisition"])     # NGIS Referral Id
spm_ids = {i["type"]["coding"][0]["code"]: f"{i['value']}&{i['assigner']['identifier']['value']}" if "assigner" in i else i["value"]
           for i in specimen["identifier"]}
specimen_type = specimen["type"]["coding"][0]

expected_segments = [
    f"MSH|^~\\&|NEYGenomics|{glh_ods}|RIE|{NW_GLH_ODS}|{datetime.now().strftime('%Y%m%d%H%M%S')}+0000||OML^O21^OML_O21|{order_bundle['identifier']['value']}|T|2.5.1|||AL",
    f"PID|1||{row['patient_nhs_number']}^^^NHS^NH~{ngis_identifier['value']}^^^{ngis_identifier['assigner']['identifier']['value']}^PI"
    f"||{patient_surname}^{patient_forename}^^^^^L||{v2_date(row['patient_date_of_birth'])}",
    f"ORC|NW|{placer_order_number}||{placer_group_number}" + "|" * 17 + f"^^{glh_ods}^^^ODS",
    f"OBR|1|{placer_order_number}||{row['clinical_indication_test_type_id']}^^England-GenomicTestDirectory",
]
if "note" in service_request:
    expected_segments.append(f"NTE|1||{service_request['note'][0]['text']}")
for n, (code_, value) in enumerate([
    ("NGIS_REFERRAL_ID", row["referral_id"]),
    ("DISPATCHED_SAMPLE_LSID", row["dispatched_sample_lsid"]),
    ("FAMILY_STRUCTURE", local_extension["family_structure"]),
    ("PARTICIPANT_TYPE", local_extension["participant_type"]),
], start=1):
    expected_segments.append(f"OBX|{n}|ST|{code_}||{value}||||||F")
expected_segments.append(
    f"SPM|1|{spm_ids['PLAC']}^{spm_ids['FILL']}||{specimen_type['code']}^{specimen_type.get('display', '')}^SCT"
    + "|" * 13 + f"{v2_datetime(row['received_sample_collection_date']) if row['received_sample_collection_date'] else ''}|{v2_datetime(row['primary_sample_received_date'])}"
)
expected_v2 = "\r".join(expected_segments) + "\r"

expected_filename = order_filename.replace(".json", "-expected.txt")
with open("Output/V2/O21/" + expected_filename, "w", newline="") as f:
    f.write(expected_v2)

print("Saved Output/V2/O21/" + expected_filename + " (hand-built expectation, not transform output)\n")
print(expected_v2.replace("\r", "\n"))

Saved Output/V2/O21/dWGS_r26000000201-expected.txt (hand-built expectation, not transform output)

MSH|^~\&|NEYGenomics|699N0|RIE|699X0|20261019113627+0000||OML^O21^OML_O21|urn:uuid:c901a0b1-4812-4b0c-bc46-5cef269ff266|T|2.5.1|||AL
PID|1||9737383222^^^NHS^NH~p26000000101^^^8J834^PI||LEEDS^Rob^^^^^L||19780117
ORC|NW|4000000001^699N0||r26000000201^8J834|||||||||||||||||^^699N0^^^ODS
OBR|1|4000000001^699N0||R14.1^^England-GenomicTestDirectory
NTE|1||Suspected inherited neurodevelopmental condition.
OBX|1|ST|NGIS_REFERRAL_ID||r26000000201||||||F
OBX|2|ST|DISPATCHED_SAMPLE_LSID||4000000001||||||F
OBX|3|ST|FAMILY_STRUCTURE||Singleton||||||F
OBX|4|ST|PARTICIPANT_TYPE||Proband||||||F
SPM|1|S26-1A01&RR8^S26-1A01&699N0||258580003^Whole blood specimen (specimen)^SCT|||||||||||||20260818000000+0000|20260820000000+0000

In [18]:
with open("Input/FHIR/O21/" + order_filename, "rb") as f:
    order_json = f.read()

rV2 = requests.post(toolsServer + "/transformToV2", data=order_json, verify=False, headers={"Content-Type": "application/fhir+json"})

print(rV2.status_code)

v2_filename = order_filename.replace(".json", ".txt")
with open("Output/V2/O21/" + v2_filename, "w") as f:
    f.write(rV2.text)

print(rV2.text)

200

In [19]:
def v2_field(message, segment, field):
    """First occurrence of SEGMENT-field (1-based, MSH not special-cased - only used on ORC/OBR/PID)."""
    for seg in message.replace("\n", "\r").split("\r"):
        parts = seg.split("|")
        if parts[0] == segment:
            return parts[field] if field < len(parts) else ""
    return None


order_number_fields = [("PID", 3), ("ORC", 2), ("ORC", 3), ("ORC", 4), ("OBR", 2), ("OBR", 3)]
pd.DataFrame([
    {"field": f"{seg}-{n}", "expected": v2_field(expected_v2, seg, n), "transform": v2_field(rV2.text, seg, n),
     "match": v2_field(expected_v2, seg, n) == v2_field(rV2.text, seg, n)}
    for seg, n in order_number_fields
])

,field,expected,transform,match
0,PID-3,9737383222^^^NHS^NH~p26000000101^^^8J834^PI,9737383222^^^NHS^NH~~p26000000101^^^8J834^PI,False
1,ORC-2,4000000001^699N0,4000000001^699N0,True
2,ORC-3,,,True
3,ORC-4,r26000000201^8J834,r26000000201^8J834,True
4,OBR-2,4000000001^699N0,4000000001^699N0,True
5,OBR-3,,,True

### Sending the order onward

`Testing.ipynb`'s `O21`/`O01` loops already `POST` their bundles to `FHIR_SERVER`'s
`$process-message` endpoint after building them, using an OAuth2 client-credentials
token (`OAUTH2_TOKEN`/`CLIENT_ID`/`CLIENT_SECRET` from `.env`) - this worked example
does the same for `order_bundle` below, something an earlier version of this section
said wasn't exercised here.

That earlier version's reasoning doesn't hold up: a first attempt at this exact call
hung indefinitely with no response at all, long enough to look like a genuine
cross-organisation firewall block between NE&Y Genomics and NW Genomics'
`FHIR_SERVER`. But `V2_TOOLS`'s own `/transformToV2` endpoint was independently
timing out the same way at the same time, then answering normally again a few
checks later with no change on this notebook's side - so both endpoints were
cycling between healthy and unresponsive, and the `$process-message` hang was that
same infrastructure flakiness, not a network boundary. Repeating the call once
`V2_TOOLS` had settled succeeded immediately (see below). **Still worth tracking for
the real implementation**: production delivery for this inter-organisation route is
expected to go via a message queue (AWS SQS) rather than a direct synchronous HTTP
POST regardless, so intermittent reachability like this wouldn't be this route's
problem in practice.

In [14]:
from requests.auth import HTTPBasicAuth

fhirServer = os.getenv("FHIR_SERVER")
tokenUrl = os.getenv("OAUTH2_TOKEN")
clientId = os.getenv("CLIENT_ID")
clientSecret = os.getenv("CLIENT_SECRET")

token_response = requests.post(
    tokenUrl,
    auth=HTTPBasicAuth(clientId, clientSecret),
    verify=False,
    data={"grant_type": "client_credentials", "scope": "system/*.*"},
    headers={"Content-Type": "application/x-www-form-urlencoded"},
)
token = token_response.json()["access_token"]

rProcessMessage = requests.post(
    fhirServer + "$process-message",
    data=order_json,
    verify=False,
    headers={"Content-Type": "application/fhir+json", "Authorization": "Bearer " + token},
)

print(rProcessMessage.status_code)
print(json.dumps(rProcessMessage.json(), indent=2))

/Users/kevinmayfield/github/MFT/Testing/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.62'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/kevinmayfield/github/MFT/Testing/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.62'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

200
{
  "resourceType": "Bundle",
  "entry": [
    {
      "fullUrl": "urn:uuid:15d00b47-ab96-4a35-a584-64d8d0e9dbec",
      "resource": {
        "resourceType": "MessageHeader",
        "destination": [
          {
            "receiver": {
              "identifier": {
                "system": "https://fhir.nhs.uk/Id/ods-organization-code",
                "value": "699C0"
              }
            }
          }
        ],
        "eventCoding": {
          "code": "O21",
          "system": "http://terminology.hl7.org/CodeSystem/v2-0003"
        },
        "response": {
          "code": "ok",
          "details": {
            "reference": "urn:uuid:34872447-65fa-48f2-874b-91eac794eeda"
          },
          "identifier": "urn:uuid:a22edb38-f8c1-4af3-99ad-9501f93a72e4"
        },
        "sender": {
          "identifier": {
            "system": "https://fhir.nhs.uk/Id/ods-organization-code",
            "value": "X24"
          }
        },
        "source": {
          "endpoint": "https://fhir.nwgenomics.nhs.uk/Endpoint/RIE",
          "software": "NW GLH Regional Integration Engine"
        }
      }
    },
    {
      "fullUrl": "urn:uuid:34872447-65fa-48f2-874b-91eac794eeda",
      "resource": {
        "resourceType": "OperationOutcome",
        "issue": [
          {
            "code": "incomplete",
            "diagnostics": "MSH|^~\\&|NEYGenomics|699C0|RIE|699X0|20260829054509+0000||OML^O21^OML_O21|urn:uuid:a22edb38-f8c1-4af3-99ad-9501f93a72e4|T|2.5.1|||AL\rPID|1||9737383222^^^NHS^NH~~p26000000101^^^8J834^PI||Leeds^Rob^^^^^L||19780117\rORC|NW|r26000000201^699C0||r26000000201^699C0|||||||||||||||||^^699C0^^^ODS\rOBR|1|r26000000201^699C0||R14.1^^England-GenomicTestDirectory||||||||||||\rNTE|1||Suspected inherited neurodevelopmental condition.\rOBX|1|ST|^Family Structure||Singleton||||||F\rOBX|2|ST|^Participant Type||Proband||||||F\rOBX|3|ST|ZCID||FX000000001||||||F\rSPM|1|RR8-P0001&RR8^YNE26-P0001&699C0||258580003^Whole blood specimen (specimen)^SNM3|||||||||||||20260818000000+0000|20260820000000+0000||||||||||||||NEY-CONSIGN-2026-100&699C0\r",
            "severity": "information"
          }
        ]
      }
    }
  ],
  "identifier": {
    "value": "1064664"
  },
  "timestamp": "2026-08-29T04:46:16.115+01:00",
  "type": "message"
}

`$process-message` accepts `order_bundle` and returns `200` with `response.code`
`"ok"` - the RIE confirms receipt rather than rejecting or silently dropping it. Its
`OperationOutcome` carries an `information`-severity `diagnostics` entry, not an
error - the RIE's own re-derived v2 message.

That echoed message matches `/transformToV2`'s own output above field-for-field
(same `SPM-2` components, same `OBX|3|ST|ZCID` container identifier, same trailing
consignment-number field) - so the RIE's `$process-message` route and `V2_TOOLS`'s
standalone `/transformToV2` endpoint are doing the same mapping for this input, not
two different ones. (An earlier run within this same session, before `V2_TOOLS`
briefly went unresponsive and came back - see above - showed the two disagreeing:
`/transformToV2` alone dropped `primary_sample_id_in_glh_lims`, the `FILL`-coded
LIMS Sample Identifier, that `$process-message`'s RIE mapping carried through fine.
Whatever changed server-side during that gap fixed `/transformToV2` to match - see
the discrepancy check below.)

One difference does remain: the response's `MessageHeader.sender` is a fixed RIE
identity (ODS `X24`), not an echo of `order_bundle`'s own `sender` - it's replying as
itself, not relaying the original message header back.

## Checking the transform

A `200` back doesn't mean everything survived the trip - check every field value this
notebook put into the FHIR `Bundle` for whether it actually shows up somewhere in the
v2 message `/transformToV2` returned above.

In [20]:
check_values = {
    "referral_id (requisition)": row["referral_id"],
    "Order Placer Number - LSID (identifier)": order_identifier["value"],
    "clinical_indication_test_type_id (ServiceRequest.code)": row["clinical_indication_test_type_id"],
    "patient_nhs_number": row["patient_nhs_number"],
    "patient_forename (PDS)": patient_forename,
    "patient_surname (PDS)": patient_surname,
    "ordering_entity_id (requester ODS)": row["ordering_entity_id"],
    "primary_sample_id_as_received_by_glh": row["primary_sample_id_as_received_by_glh"],
    "primary_sample_id_in_glh_lims": row["primary_sample_id_in_glh_lims"],
    "primary_sample_state (Specimen.type coding)": primary_sample_type_display,
    "dispatched_sample_lsid (container.identifier)": row["dispatched_sample_lsid"],
    "dispatched_sample_state (Specimen.type text)": row["dispatched_sample_state"],
    "dna_extraction_protocol (collection.method)": row["dna_extraction_protocol"],
    "dispatched_sample_volume_(ul) (collection.quantity)": row["dispatched_sample_volume_(ul)"],
    "glh_sample_consignment_number": row["glh_sample_consignment_number"],
    "family_structure (Group.code)": family_structure_code,
    "participant_type (Group.member relationship)": relationship_code,
    "clinical_information (local-extension stand-in)": local_extension["clinical_information"],
    "approved_by (PractitionerRole.practitioner.display)": row["approved_by"],
    "NE&Y Genomics sender ODS": glh_ods,
    "NW Genomics destination ODS": NW_GLH_ODS,
}

pd.DataFrame(
    [{"field": field, "value": value, "present_in_v2": value in rV2.text} for field, value in check_values.items()]
)

,field,value,present_in_v2
0,referral_id (requisition),r26000000201,True
1,Order Placer Number - LSID (identifier),4000000001,True
2,clinical_indication_test_type_id (ServiceReque...,R14.1,True
3,patient_nhs_number,9737383222,True
4,patient_forename (PDS),Rob,True
5,patient_surname (PDS),LEEDS,True
6,ordering_entity_id (requester ODS),RR8,True
7,primary_sample_id_as_received_by_glh,S26-1A01,True
8,primary_sample_id_in_glh_lims,S26-1A01,True
9,primary_sample_state (Specimen.type coding),Whole blood specimen (specimen),True
10,dispatched_sample_lsid (container.identifier),4000000001,True
11,dispatched_sample_state (Specimen.type text),DNA,False
12,dna_extraction_protocol (collection.method),,True
13,dispatched_sample_volume_(ul) (collection.quan...,150.0,False
14,glh_sample_consignment_number,NEY GLH 2026-08-26,True
15,family_structure (Group.code),FamilyStructureSingleton,False
16,participant_type (Group.member relationship),ONESELF,False
17,clinical_information (local-extension stand-in),Suspected inherited neurodevelopmental condition.,True
18,approved_by (PractitionerRole.practitioner.dis...,Duty Scientist on behalf of NEYGLH Medical,False
19,NE&Y Genomics sender ODS,699N0,True
20,NW Genomics destination ODS,699X0,True

> **Re-run (LSID Order Placer Number pass, IG 2.2.1).** `/transformToV2` and the two
> check cells above were re-run against the `FamilyGeneticGroup`/LSID `Bundle`.
> `$process-message` (`FHIR_SERVER`) was not re-run, so its output above is still from the
> earlier `Observation`-based `Bundle`. The order-number comparison now matches on
> `ORC-2`/`OBR-2` (`<LSID>^<GLH ODS>`, e.g. `4000000001^699N0`), `ORC-3`/`OBR-3` (empty)
> and `ORC-4` (`r…^8J834`). The one mismatch is `PID-3`, where the transform emits an
> empty repetition (`…^NH~~p…`) that the hand-built expectation doesn't. The transform
> did this before this pass too. The discrepancy check above shows the `Group` isn't
> carried into v2: `family_structure` and `participant_type` both come back `False` (no
> `OBX` `FAMILY_STRUCTURE`/`PARTICIPANT_TYPE`), and so does `approved_by`.
> `dispatched_sample_state` and `dispatched_sample_volume_(ul)` are also `False`. The
> paragraph below describes the earlier `Observation` runs.

Coding the `Specimen` identifiers' `type` (`PLAC`/`FILL`/`STN`) and `Specimen.type`
itself (a real SNOMED CT code from `Input/dWGS.csv` now, not free text), plus coding
`container.identifier.type` as `ZCID`, now accounts for every field this table checks
except one. `PLAC` (Received Sample Identifier), `STN` (Shipment Tracking Number),
`FILL` (LIMS Sample Identifier), `Specimen.type`, and `container.identifier` (the
dispatched-sample barcode, `ZCID`-coded above) all come through -
`ordering_entity_id`, `primary_sample_id_as_received_by_glh`,
`primary_sample_id_in_glh_lims`, `primary_sample_state`, and
`dispatched_sample_lsid` all flip from `False` to `True` across this notebook's
passes. `FILL` was the last holdout: an earlier run within this same session still
recorded it `False` here even though `$process-message`'s RIE mapping already carried
it through (see above) - a real difference between the two entry points at the time,
not a coding gap on this notebook's side. Something changed server-side between that
run and this one (`V2_TOOLS` was intermittently unresponsive in between - see above)
that brought `/transformToV2` alone in line with `$process-message`. The two "ask at
order" `Observation.valueCodeableConcept`s (`family_structure`, `participant_type`)
flipped the same way, for the same reason: nothing in this worked example's own code
changed across those runs, so both flips reflect the live transform service's
evolving behaviour, not this notebook - a reminder that this check exercises a real,
evolving system rather than a fixed target. This pass adds two new fields, and finds a
genuine gap rather than a flip: `dna_extraction_protocol` (`Specimen.collection.method`)
and `dispatched_sample_volume_(ul)` (`Specimen.collection.quantity`) both build and
validate cleanly, but neither survives into the v2 output - `SPM-7`/`SPM-12` stay blank
rather than carrying `"Qiagen"`/`120`, unlike everything else `Specimen.collection`
already carried (`collectedDateTime` lands correctly). Whether that's the same kind of
transform-mapping gap `FILL` briefly was, or something this pass's fields never had
support for, isn't something this single run can tell. `dispatched_sample_state` (not
built into any resource at all, coded or not) remains the one field that vanishes for a
known, unrelated reason. Every genuinely coded value elsewhere (NHS number, ODS codes
on `MessageHeader`/`requester`, the Genomic Test Directory code) comes through fine
throughout.

## Look forward: what comes back

This order is one half of a closed loop - [NW-GMSA's ILW
page](https://nw-gmsa.github.io/en/ILW.html) pairs this `LAB-35` sub-order with a
`LAB-36` result coming back the other way. Which shape that result takes depends on
what the requester actually needs:

- **A PDF report** - `LAB-3` (`ORU^R01`/FHIR `R01` Message), the narrative report
  `04-laboratory-report-fhir-from-hl7v2.ipynb` builds.
- **Structured variants** - `LAB-5` (`ORU^R01`/FHIR `R01` Message), the discrete
  genomic findings `05-test-results-from-vcf.ipynb` builds.
- **Both together** - an XD-LAB/FHIR Document, combining a PDF and structured results
  in one document `Bundle`, which `06-eu-laboratory-report-fhir-document.ipynb` builds.
  This is the shape most likely to matter here: it's the format NHS England's Unified
  Genomic Record (UGR) is expected to use.

## Closing note

This is a preparation/analysis notebook, not a settled spec. Running the worked example
above already surfaced real findings this notebook's earlier analysis alone hadn't:
corrections to the field-mapping table (`family_structure`/`participant_type` moving
from a guessed extension to `Observation`/`supportingInfo`, and then - once the IG
introduced it - to a `FamilyGeneticGroup` linked by `requisition`, `glh_laboratory_id` moving
off `ServiceRequest.requester` onto `MessageHeader.sender`), a structural `Patient`
mistake that failed the *entire* v2 transform with no explanation until the FHIR
validation step caught it, and - via the discrepancy check - confirmation that
text-only values reliably vanish in that same transform while coded ones survive,
a live example of the target transform service itself changing mid-session
(`FILL`, `family_structure`, and `participant_type` all flipping from vanishing to
surviving between two runs of the exact same code), and - from this pass's two new
`Specimen.collection` fields - a fresh, still-open gap of the same shape: correctly
built and validated FHIR that doesn't survive into `SPM-7`/`SPM-12` regardless - not
something coding the identifiers was expected to leave open, but a real property of
testing against a live system rather than a fixed target. Exactly the kind of thing this notebook is *for*.
Expect further passes to
keep finding gaps like these, which may in turn mean `Input/dWGS.csv` itself needs
updating (new columns, corrected values) - which would then change this worked example
again. That loop is the intended way this notebook gets used, not a sign something went
wrong.

## Additional data: fields not in this worked example

`Input/dWGS.csv` covers the 37 national manifest fields. The worked example above adds
the patient's name from PDS and stand-ins for three of the NW GMS local-extension fields
(see [Sample manifest data](#Sample-manifest-data)). `placer_order_number` (one of the
two local-extension fields the v0.2 spec added) is built from `dispatched_sample_lsid`;
`patient_medical_record_number` has no source yet and isn't built. Beyond those, further fields may be added to the
payload - mainly to help the *original* order placer (the referring NHS Trust) and
order filler (the Requesting Genomic Laboratory) track this sub-order, rather than
anything NW Genomics (and Genomics England Limited) itself needs to fulfil it. None of these are built into the
worked example above - documented here as a reference for a future pass, not
implemented:

- **Medical Record Number (MRN)**, a.k.a. hospital number - usually a Trust's primary
  patient identifier. See
  [`Patient`](https://nw-gmsa.github.io/en/StructureDefinition-Patient.html).
- **Account Number / Visit Number**, a.k.a. Hospital Spell Identifier - links every
  diagnostic order from the same episode together, the same role `referral_id` plays
  for this sub-order. See the `encounter` element on
  [`ServiceRequest`](https://nw-gmsa.github.io/en/StructureDefinition-ServiceRequest.html).
  Can be very useful to the ordering NHS Trust, and in some cases is required by them.
- **Order Placer Number** - an identifier assigned by `ordering_entity_id` (the
  referring Trust). Helps the Trust match orders to reports; in some cases required by
  them. See [`ServiceRequest`](https://nw-gmsa.github.io/en/StructureDefinition-ServiceRequest.html).
- **Order Filler Number** - an identifier assigned by the Order Placer/Requesting
  Genomic Laboratory. Useful for tracking orders and reports. See
  [`ServiceRequest`](https://nw-gmsa.github.io/en/StructureDefinition-ServiceRequest.html).
- **Duo/Trio relationship details** - how a family member is related to the proband
  (mother, father, sibling...), not just that `participant_type` says "Family Member".
  `FamilyGeneticGroup`'s `FamilyMemberRelationship` extension already has room for this
  (`MTH`, `FTH`, `SIB`... from the RelatedPerson Relationship Type value set). This
  worked example falls back to the generic `FAMMEMB` only because the local-extension
  `participant_type` doesn't carry it. Rather than a new manifest column, the more likely
  source is NHS England: PDS's
  [`GET /Patient/{id}/RelatedPerson`](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir#get-/Patient/-id-/RelatedPerson)
  or the
  [Related Person Network FHIR API](https://digital.nhs.uk/developer/api-catalogue/related-person-network---fhir-api),
  queried by NHS number. Either could supply the specific relationship. It could then be
  coded on the `Group` member's relationship (or as `RelatedPerson` resources) with no
  change to the model.

### On making Order Number mandatory

`ServiceRequest.identifier` (Order Number) may need to become a mandatory field -
either an Order Placer Number or an Order Filler Number would be sufficient on its own.
An earlier pass used the Automation Manager's (Genomics England Limited) own
`referral_id` and `patient_ngis_id` combined as an Order Filler Number assigned by
Genomics England (ODS `8J834`), `f"{referral_id}-{patient_ngis_id}"`, which the IG
published as
the NGIS Composite Order Number (since removed from the IG).
It isn't unique per order (a cancer referral's germline and tumour rows share it), so
the worked example above now builds the Order Placer Number from `dispatched_sample_lsid`
instead, assigned by the sending lab (see the ServiceRequest section).